trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
  paths:
    include:
      - eng/
      - extensions/Worker.Extensions.Storage/
      - test/Worker.Extensions.Tests/

# CI only, does not trigger on PRs.
pr: none

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/build.yml@eng
  - template: ci/variables/cfs.yml@eng
  - name: ExtensionProjectName
    value: Worker.Extensions.Storage

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows

    stages:

    - stage: BuildTest
      displayName: 'Build & Test'

      jobs:
      - template: /eng/ci/templates/official/jobs/build-extension-artifacts.yml@self
        parameters:
          ExtensionProjectName: $(ExtensionProjectName)

      - template: /eng/ci/templates/jobs/run-extension-tests.yml@self
        parameters:
          ExtensionProjectName: $(ExtensionProjectName)
          HasOwnTestProject: false
