# This build is used for public PR and CI builds.

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - feature/*
  paths:
    include:
      - extensions/Worker.Extensions.Storage/

pr:
  branches:
    include:
    - main
    - release/*
    - feature/*
  include:
    - extensions/Worker.Extensions.Storage/

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - template: /eng/ci/templates/variables/build.yml@self
  - name: ExtensionProjectName
    value: Worker.Extensions.Storage

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: Test

      jobs:
      - template: /eng/ci/templates/jobs/run-extension-tests.yml@self
        parameters:
          ExtensionProjectName: $(ExtensionProjectName)
          HasOwnTestProject: false
