parameters:
- name: publishToNugetOrg
  displayName: Publish to nuget.org?
  type: boolean
  default: false

pr: none
trigger: none

resources:
  pipelines:
  - pipeline: build
    source: extensions.servicebus.official

extends:
  template: /eng/ci/templates/pipelines/release-extension-packages.yml@self
  parameters:
    publishToNugetOrg: ${{ parameters.publishToNugetOrg }}
    targetFolder: worker-extensions/servicebus
