parameters:
- name: publishToNugetOrg
  displayName: Publish to nuget.org?
  type: boolean
  default: false

pr: none
trigger: none

extends:
  template: /eng/ci/templates/pipelines/release-extension-packages.yml@self
  parameters:
    publishToNugetOrg: ${{ parameters.publishToNugetOrg }}
    pipelineName: extensions.servicebus.official
