// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Worker.Sdk.Generators;
using Xunit;

namespace Microsoft.Azure.Functions.SdkGeneratorTests
{
    public class FunctionMetadataProviderGeneratorTests
    {
        private Assembly[] referencedExtensionAssemblies;

        public FunctionMetadataProviderGeneratorTests()
        {
            // load all extensions used in tests (match extensions tested on E2E app? Or include ALL extensions?)
            var abstractionsExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.Abstractions.dll");
            var httpExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.Http.dll");
            var storageExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.Storage.dll");
            var cosmosDBExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.CosmosDB.dll");
            var timerExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.Timer.dll");
            var eventHubsExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.EventHubs.dll");
            var blobExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.Storage.Blobs.dll");
            var queueExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues.dll");
            var loggerExtension = Assembly.LoadFrom("Microsoft.Extensions.Logging.Abstractions.dll");
            var hostingExtension = Assembly.LoadFrom("Microsoft.Extensions.Hosting.dll");
            var diExtension = Assembly.LoadFrom("Microsoft.Extensions.DependencyInjection.dll");
            var hostingAbExtension = Assembly.LoadFrom("Microsoft.Extensions.Hosting.Abstractions.dll");
            var diAbExtension = Assembly.LoadFrom("Microsoft.Extensions.DependencyInjection.Abstractions.dll");

            referencedExtensionAssemblies = new[]
            {
                abstractionsExtension,
                httpExtension,
                storageExtension,
                cosmosDBExtension,
                timerExtension,
                eventHubsExtension,
                blobExtension,
                queueExtension,
                loggerExtension,
                hostingExtension,
                hostingAbExtension,
                diExtension,
                diAbExtension
            };

        }

        [Fact]
        public async Task GenerateSimpleHttpTriggerMetadataTest()
        {
            // test generating function metadata for a simple HttpTrigger
            string inputCode = @"
            using System;
            using System.Collections.Generic;
            using System.Diagnostics;
            using System.Net;
            using Microsoft.Azure.Functions.Worker;
            using Microsoft.Azure.Functions.Worker.Http;
            using Microsoft.Extensions.Logging;

            namespace FunctionApp
            {
                public static class HttpTriggerSimple
                {
                    [Function(nameof(HttpTriggerSimple))]
                    public static HttpResponseData Run([HttpTrigger(AuthorizationLevel.Anonymous, ""get"", ""post"", Route = null)] HttpRequestData req, FunctionContext executionContext)
                    {
                        var sw = new Stopwatch();
                    sw.Restart();

                        var logger = executionContext.GetLogger(""FunctionApp.HttpTriggerSimple"");
                    logger.LogInformation(""Message logged"");

                        var response = req.CreateResponse(HttpStatusCode.OK);

                    response.Headers.Add(""Date"", ""Mon, 18 Jul 2016 16:06:00 GMT"");
                        response.Headers.Add(""Content-Type"", ""text/html; charset=utf-8"");
                        response.WriteString(""Hello world!"");

                        logger.LogMetric(@""funcExecutionTimeMs"", sw.Elapsed.TotalMilliseconds,
                            new Dictionary<string, object> {
                                { ""foo"", ""bar""},
                                { ""baz"", 42 }
                            }
                        );

                        return response;
                    }
                }
            }";

  
            string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
            string expectedOutput = @"// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Core;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
namespace Microsoft.Azure.Functions.Worker
{
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            var metadataList = new List<IFunctionMetadata>();
            var HttpTriggerSimpleRawBindings = new List<string>();
            var HttpTriggerSimplereqBinding = new {
                name = 'req',
                type = 'HttpTrigger',
                direction = 'In',
                authLevel = (AuthorizationLevel)0,
                methods = new List<string> { 'get','post' },
            };
            var HttpTriggerSimplereqBindingJSONstring = JsonSerializer.Serialize(HttpTriggerSimplereqBinding);
            HttpTriggerSimpleRawBindings.Add(HttpTriggerSimplereqBindingJSONstring);
            var HttpTriggerSimplereturnBinding = new {
                name = '$return',
                type = 'http',
                direction = 'Out',
            };
            var HttpTriggerSimplereturnBindingJSONstring = JsonSerializer.Serialize(HttpTriggerSimplereturnBinding);
            HttpTriggerSimpleRawBindings.Add(HttpTriggerSimplereturnBindingJSONstring);
            var HttpTriggerSimple = new DefaultFunctionMetadata
            {
                FunctionId = Guid.NewGuid().ToString(),
                Language = 'dotnet-isolated',
                Name = 'HttpTriggerSimple',
                EntryPoint = 'TestProject.HttpTriggerSimple.Run',
                RawBindings = HttpTriggerSimpleRawBindings,
                ScriptFile = 'TestProject.dll'
            };
            metadataList.Add(HttpTriggerSimple);
            return Task.FromResult(metadataList.ToImmutableArray());
        }
        public enum AuthorizationLevel
        {
            Anonymous,
            User,
            Function,
            System,
            Admin
        }
    }
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}
".Replace("'", "\"");

            await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                referencedExtensionAssemblies,
                inputCode,
                expectedGeneratedFileName,
                expectedOutput);
        }

        [Fact]
        public async Task GenerateFunctionWhereOutputBindingIsInTheReturnTypeTest()
        {
            // test generating function metadata for a simple HttpTrigger
            string inputCode = @"
            using System.Net;
            using Microsoft.Azure.Functions.Worker;
            using Microsoft.Azure.Functions.Worker.Http;

            namespace FunctionApp
            {
                public static class HttpTriggerWithMultipleOutputBindings
                {
                    [Function(nameof(HttpTriggerWithMultipleOutputBindings))]
                    public static MyOutputType Run([HttpTrigger(AuthorizationLevel.Anonymous, ""get"", ""post"", Route = null)] HttpRequestData req,
                        FunctionContext context)
                    {
                        var response = req.CreateResponse(HttpStatusCode.OK);
                        response.WriteString(""Success!"");

                        return new MyOutputType()
                        {
                            Name = ""some name"",
                            HttpResponse = response
                        };
                    }
                }

                public class MyOutputType
                {
                    [QueueOutput(""functionstesting2"", Connection = ""AzureWebJobsStorage"")]
                    public string Name { get; set; }

                    public HttpResponseData HttpResponse { get; set; }
                }
            }";


            string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
            string expectedOutput = @"// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Core;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
namespace Microsoft.Azure.Functions.Worker
{
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            var metadataList = new List<IFunctionMetadata>();
            var HttpTriggerWithMultipleOutputBindingsRawBindings = new List<string>();
            var HttpTriggerWithMultipleOutputBindingsreqBinding = new {
                name = 'req',
                type = 'HttpTrigger',
                direction = 'In',
                authLevel = (AuthorizationLevel)0,
                methods = new List<string> { 'get','post' },
            };
            var HttpTriggerWithMultipleOutputBindingsreqBindingJSONstring = JsonSerializer.Serialize(HttpTriggerWithMultipleOutputBindingsreqBinding);
            HttpTriggerWithMultipleOutputBindingsRawBindings.Add(HttpTriggerWithMultipleOutputBindingsreqBindingJSONstring);
            var HttpTriggerWithMultipleOutputBindingsNameBinding = new {
                name = 'Name',
                type = 'Queue',
                direction = 'Out',
                queueName = 'functionstesting2',
                Connection = 'AzureWebJobsStorage',
                dataType = 'String',
            };
            var HttpTriggerWithMultipleOutputBindingsNameBindingJSONstring = JsonSerializer.Serialize(HttpTriggerWithMultipleOutputBindingsNameBinding);
            HttpTriggerWithMultipleOutputBindingsRawBindings.Add(HttpTriggerWithMultipleOutputBindingsNameBindingJSONstring);
            var HttpTriggerWithMultipleOutputBindingsHttpResponseBinding = new {
                name = 'HttpResponse',
                type = 'http',
                direction = 'Out',
            };
            var HttpTriggerWithMultipleOutputBindingsHttpResponseBindingJSONstring = JsonSerializer.Serialize(HttpTriggerWithMultipleOutputBindingsHttpResponseBinding);
            HttpTriggerWithMultipleOutputBindingsRawBindings.Add(HttpTriggerWithMultipleOutputBindingsHttpResponseBindingJSONstring);
            var HttpTriggerWithMultipleOutputBindings = new DefaultFunctionMetadata
            {
                FunctionId = Guid.NewGuid().ToString(),
                Language = 'dotnet-isolated',
                Name = 'HttpTriggerWithMultipleOutputBindings',
                EntryPoint = 'TestProject.HttpTriggerWithMultipleOutputBindings.Run',
                RawBindings = HttpTriggerWithMultipleOutputBindingsRawBindings,
                ScriptFile = 'TestProject.dll'
            };
            metadataList.Add(HttpTriggerWithMultipleOutputBindings);
            return Task.FromResult(metadataList.ToImmutableArray());
        }
        public enum AuthorizationLevel
        {
            Anonymous,
            User,
            Function,
            System,
            Admin
        }
    }
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}
".Replace("'", "\"");

            await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                referencedExtensionAssemblies,
                inputCode,
                expectedGeneratedFileName,
                expectedOutput);
        }

        [Fact]
        public async Task FunctionWithStringDataTypeInputBindingTest()
        {
            string inputCode = @"
            using System.Net;
            using System.Text.Json;
            using Microsoft.Azure.Functions.Worker;
            using Microsoft.Azure.Functions.Worker.Http;

            namespace FunctionApp
            {
                public static class HttpTriggerWithBlobInput
                {
                    [Function(nameof(HttpTriggerWithBlobInput))]
                    public static MyOutputType Run(
                        [HttpTrigger(AuthorizationLevel.Anonymous, 'get', 'post', Route = null)] HttpRequestData req,
                        [BlobInput('test-samples/sample1.txt', Connection = 'AzureWebJobsStorage')] string myBlob, FunctionContext context)
                    {
                        var bookVal = (Book)JsonSerializer.Deserialize(myBlob, typeof(Book));

                        var response = req.CreateResponse(HttpStatusCode.OK);

                        response.Headers.Add('Date', 'Mon, 18 Jul 2016 16:06:00 GMT');
                        response.Headers.Add('Content-Type', 'text/html; charset=utf-8');
                        response.WriteString('Book Sent to Queue!');

                        return new MyOutputType()
                        {
                            Book = bookVal,
                            HttpResponse = response
                        };
                    }

                    public class MyOutputType
                    {
                        [QueueOutput('functionstesting2', Connection = 'AzureWebJobsStorage')]
                        public Book Book { get; set; }

                        public HttpResponseData HttpResponse { get; set; }
                    }

                    public class Book
                    {
                        public string name { get; set; }
                        public string id { get; set; }
                    }
                }
            }".Replace("'", "\"");

            string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
            string expectedOutput = @"// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Core;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
namespace Microsoft.Azure.Functions.Worker
{
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            var metadataList = new List<IFunctionMetadata>();
            var HttpTriggerWithBlobInputRawBindings = new List<string>();
            var HttpTriggerWithBlobInputreqBinding = new {
                name = 'req',
                type = 'HttpTrigger',
                direction = 'In',
                authLevel = (AuthorizationLevel)0,
                methods = new List<string> { 'get','post' },
            };
            var HttpTriggerWithBlobInputreqBindingJSONstring = JsonSerializer.Serialize(HttpTriggerWithBlobInputreqBinding);
            HttpTriggerWithBlobInputRawBindings.Add(HttpTriggerWithBlobInputreqBindingJSONstring);
            var HttpTriggerWithBlobInputmyBlobBinding = new {
                name = 'myBlob',
                type = 'Blob',
                direction = 'In',
                blobPath = 'test-samples/sample1.txt',
                Connection = 'AzureWebJobsStorage',
                dataType = 'String',
            };
            var HttpTriggerWithBlobInputmyBlobBindingJSONstring = JsonSerializer.Serialize(HttpTriggerWithBlobInputmyBlobBinding);
            HttpTriggerWithBlobInputRawBindings.Add(HttpTriggerWithBlobInputmyBlobBindingJSONstring);
            var HttpTriggerWithBlobInputBookBinding = new {
                name = 'Book',
                type = 'Queue',
                direction = 'Out',
                queueName = 'functionstesting2',
                Connection = 'AzureWebJobsStorage',
            };
            var HttpTriggerWithBlobInputBookBindingJSONstring = JsonSerializer.Serialize(HttpTriggerWithBlobInputBookBinding);
            HttpTriggerWithBlobInputRawBindings.Add(HttpTriggerWithBlobInputBookBindingJSONstring);
            var HttpTriggerWithBlobInputHttpResponseBinding = new {
                name = 'HttpResponse',
                type = 'http',
                direction = 'Out',
            };
            var HttpTriggerWithBlobInputHttpResponseBindingJSONstring = JsonSerializer.Serialize(HttpTriggerWithBlobInputHttpResponseBinding);
            HttpTriggerWithBlobInputRawBindings.Add(HttpTriggerWithBlobInputHttpResponseBindingJSONstring);
            var HttpTriggerWithBlobInput = new DefaultFunctionMetadata
            {
                FunctionId = Guid.NewGuid().ToString(),
                Language = 'dotnet-isolated',
                Name = 'HttpTriggerWithBlobInput',
                EntryPoint = 'TestProject.HttpTriggerWithBlobInput.Run',
                RawBindings = HttpTriggerWithBlobInputRawBindings,
                ScriptFile = 'TestProject.dll'
            };
            metadataList.Add(HttpTriggerWithBlobInput);
            return Task.FromResult(metadataList.ToImmutableArray());
        }
        public enum AuthorizationLevel
        {
            Anonymous,
            User,
            Function,
            System,
            Admin
        }
    }
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}
".Replace("'", "\"");

            await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                referencedExtensionAssemblies,
                inputCode,
                expectedGeneratedFileName,
                expectedOutput);
        }

        [Fact]
        public async Task FunctionWithNonFunctionsRelatedAttributeTest()
        {
            string inputCode = @"
            using System;
            using System.Net;
            using System.Text.Json;
            using Microsoft.Azure.Functions.Worker;
            using Microsoft.Azure.Functions.Worker.Http;

            namespace FunctionApp
            {
                public class HttpTriggerWithBlobInput
                {
                    [Function('Products')]
                    public HttpResponseData Run(
                                   [HttpTrigger(AuthorizationLevel.Anonymous, ""get"", Route = null)] HttpRequestData req,
                                   [FakeAttribute('hi')] string someString)
                    {
                        var response = req.CreateResponse(HttpStatusCode.OK);
                        response.Headers.Add(""Content-Type"", ""text/plain; charset=utf-8"");
                        return response;
                    }
                }

                public class FakeAttribute : Attribute
                {
                    public FakeAttribute(string name)
                    {
                        Name = name;
                    }

                    public string Name { get; }
                }
            }".Replace("'", "\"");

            string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
            string expectedOutput = @"// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Core;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
namespace Microsoft.Azure.Functions.Worker
{
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            var metadataList = new List<IFunctionMetadata>();
            var ProductsRawBindings = new List<string>();
            var ProductsreqBinding = new {
                name = 'req',
                type = 'HttpTrigger',
                direction = 'In',
                authLevel = (AuthorizationLevel)0,
                methods = new List<string> { 'get' },
            };
            var ProductsreqBindingJSONstring = JsonSerializer.Serialize(ProductsreqBinding);
            ProductsRawBindings.Add(ProductsreqBindingJSONstring);
            var ProductsreturnBinding = new {
                name = '$return',
                type = 'http',
                direction = 'Out',
            };
            var ProductsreturnBindingJSONstring = JsonSerializer.Serialize(ProductsreturnBinding);
            ProductsRawBindings.Add(ProductsreturnBindingJSONstring);
            var Products = new DefaultFunctionMetadata
            {
                FunctionId = Guid.NewGuid().ToString(),
                Language = 'dotnet-isolated',
                Name = 'Products',
                EntryPoint = 'TestProject.HttpTriggerWithBlobInput.Run',
                RawBindings = ProductsRawBindings,
                ScriptFile = 'TestProject.dll'
            };
            metadataList.Add(Products);
            return Task.FromResult(metadataList.ToImmutableArray());
        }
        public enum AuthorizationLevel
        {
            Anonymous,
            User,
            Function,
            System,
            Admin
        }
    }
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}
".Replace("'", "\"");

            await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                referencedExtensionAssemblies,
                inputCode,
                expectedGeneratedFileName,
                expectedOutput);
        }

        [Fact]
        public async void FunctionWithTaskReturnTypeTest()
        {
            string inputCode = @"
                using System;
                using System.Net;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Http;

                namespace FunctionApp
                {
                    public class Timer
                    {
                        [Function('TimerFunction')]
                        public Task RunTimer([TimerTrigger('0 0 0 * * *', RunOnStartup = false)] object timer)
                        {
                            throw new NotImplementedException();
                        }
                    }
                }
                ".Replace("'", "\"");

         string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
        string expectedOutput = @"// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Core;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
namespace Microsoft.Azure.Functions.Worker
{
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            var metadataList = new List<IFunctionMetadata>();
            var TimerFunctionRawBindings = new List<string>();
            var TimerFunctiontimerBinding = new {
                name = 'timer',
                type = 'TimerTrigger',
                direction = 'In',
                schedule = '0 0 0 * * *',
                RunOnStartup = 'False',
            };
            var TimerFunctiontimerBindingJSONstring = JsonSerializer.Serialize(TimerFunctiontimerBinding);
            TimerFunctionRawBindings.Add(TimerFunctiontimerBindingJSONstring);
            var TimerFunction = new DefaultFunctionMetadata
            {
                FunctionId = Guid.NewGuid().ToString(),
                Language = 'dotnet-isolated',
                Name = 'TimerFunction',
                EntryPoint = 'TestProject.Timer.RunTimer',
                RawBindings = TimerFunctionRawBindings,
                ScriptFile = 'TestProject.dll'
            };
            metadataList.Add(TimerFunction);
            return Task.FromResult(metadataList.ToImmutableArray());
        }
        public enum AuthorizationLevel
        {
            Anonymous,
            User,
            Function,
            System,
            Admin
        }
    }
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}
".Replace("'", "\"");

        await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
            referencedExtensionAssemblies,
            inputCode,
            expectedGeneratedFileName,
            expectedOutput);
        }

        [Fact]
        public async void FunctionWithGenericTaskReturnTypeTest()
        {
            string inputCode = @"
                using System;
                using System.Net;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Http;

                namespace FunctionApp
                {
                    public class BasicHttp
                    {
                        [Function('FunctionName')]
                        public Task<HttpResponseData> Http([HttpTrigger(AuthorizationLevel.Admin, 'get', 'Post', Route = '/api2')] HttpRequestData myReq)
                        {
                            throw new NotImplementedException();
                        }
                    }
                }
                ".Replace("'", "\"");

            string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
            string expectedOutput = @"// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Core;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
namespace Microsoft.Azure.Functions.Worker
{
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            var metadataList = new List<IFunctionMetadata>();
            var FunctionNameRawBindings = new List<string>();
            var FunctionNamemyReqBinding = new {
                name = 'myReq',
                type = 'HttpTrigger',
                direction = 'In',
                authLevel = (AuthorizationLevel)4,
                methods = new List<string> { 'get','Post' },
                Route = '/api2',
            };
            var FunctionNamemyReqBindingJSONstring = JsonSerializer.Serialize(FunctionNamemyReqBinding);
            FunctionNameRawBindings.Add(FunctionNamemyReqBindingJSONstring);
            var FunctionNamereturnBinding = new {
                name = '$return',
                type = 'http',
                direction = 'Out',
            };
            var FunctionNamereturnBindingJSONstring = JsonSerializer.Serialize(FunctionNamereturnBinding);
            FunctionNameRawBindings.Add(FunctionNamereturnBindingJSONstring);
            var FunctionName = new DefaultFunctionMetadata
            {
                FunctionId = Guid.NewGuid().ToString(),
                Language = 'dotnet-isolated',
                Name = 'FunctionName',
                EntryPoint = 'TestProject.BasicHttp.Http',
                RawBindings = FunctionNameRawBindings,
                ScriptFile = 'TestProject.dll'
            };
            metadataList.Add(FunctionName);
            return Task.FromResult(metadataList.ToImmutableArray());
        }
        public enum AuthorizationLevel
        {
            Anonymous,
            User,
            Function,
            System,
            Admin
        }
    }
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}
".Replace("'", "\"");

            await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                referencedExtensionAssemblies,
                inputCode,
                expectedGeneratedFileName,
                expectedOutput);
        }

        [Fact]
        public async void FunctionWithIsBatchedFalse()
        {
            string inputCode = @"
                using System;
                using System.Net;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Http;

                namespace FunctionApp
                {
                    public class EventHubStringInput
                    {
                        [Function('StringInputFunction')]
                        public static void StringInputFunction([EventHubTrigger('test', Connection = 'EventHubConnectionAppSetting', IsBatched = false)] string input,
                        FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }
                    }
                }
                ".Replace("'", "\"");

            string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
            string expectedOutput = @"// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Core;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
namespace Microsoft.Azure.Functions.Worker
{
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            var metadataList = new List<IFunctionMetadata>();
            var StringInputFunctionRawBindings = new List<string>();
            var StringInputFunctioninputBinding = new {
                name = 'input',
                type = 'EventHubTrigger',
                direction = 'In',
                eventHubName = 'test',
                Connection = 'EventHubConnectionAppSetting',
                Cardinality = 'One',
                dataType = 'String',
            };
            var StringInputFunctioninputBindingJSONstring = JsonSerializer.Serialize(StringInputFunctioninputBinding);
            StringInputFunctionRawBindings.Add(StringInputFunctioninputBindingJSONstring);
            var StringInputFunction = new DefaultFunctionMetadata
            {
                FunctionId = Guid.NewGuid().ToString(),
                Language = 'dotnet-isolated',
                Name = 'StringInputFunction',
                EntryPoint = 'TestProject.EventHubStringInput.StringInputFunction',
                RawBindings = StringInputFunctionRawBindings,
                ScriptFile = 'TestProject.dll'
            };
            metadataList.Add(StringInputFunction);
            return Task.FromResult(metadataList.ToImmutableArray());
        }
        public enum AuthorizationLevel
        {
            Anonymous,
            User,
            Function,
            System,
            Admin
        }
    }
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}
".Replace("'", "\"");

            await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                referencedExtensionAssemblies,
                inputCode,
                expectedGeneratedFileName,
                expectedOutput);
        }

        [Fact]
        public async void ValidFunctionWithIsBatchedTrue()
        {
            string inputCode = @"
                using System;
                using System.Net;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Http;

                namespace FunctionApp
                {
                    public class EventHubStringInput
                    {
                        [Function('StringInputFunction')]
                        public static void StringInputFunction([EventHubTrigger('test', Connection = 'EventHubConnectionAppSetting', IsBatched = true)] string[] input,
                        FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }
                    }
                }
                ".Replace("'", "\"");

            string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
            string expectedOutput = @"// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Core;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
namespace Microsoft.Azure.Functions.Worker
{
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            var metadataList = new List<IFunctionMetadata>();
            var StringInputFunctionRawBindings = new List<string>();
            var StringInputFunctioninputBinding = new {
                name = 'input',
                type = 'EventHubTrigger',
                direction = 'In',
                eventHubName = 'test',
                Connection = 'EventHubConnectionAppSetting',
                Cardinality = 'Many',
            };
            var StringInputFunctioninputBindingJSONstring = JsonSerializer.Serialize(StringInputFunctioninputBinding);
            StringInputFunctionRawBindings.Add(StringInputFunctioninputBindingJSONstring);
            var StringInputFunction = new DefaultFunctionMetadata
            {
                FunctionId = Guid.NewGuid().ToString(),
                Language = 'dotnet-isolated',
                Name = 'StringInputFunction',
                EntryPoint = 'TestProject.EventHubStringInput.StringInputFunction',
                RawBindings = StringInputFunctionRawBindings,
                ScriptFile = 'TestProject.dll'
            };
            metadataList.Add(StringInputFunction);
            return Task.FromResult(metadataList.ToImmutableArray());
        }
        public enum AuthorizationLevel
        {
            Anonymous,
            User,
            Function,
            System,
            Admin
        }
    }
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}
".Replace("'", "\"");

            await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                referencedExtensionAssemblies,
                inputCode,
                expectedGeneratedFileName,
                expectedOutput);
        }

        [Fact]
        public async void TestQueueWithFunctionsReturnType()
        {
            string inputCode = @"
                using System.Collections.Generic;
                using System.Linq;
                using System.Net;
                using System.Text.Json.Serialization;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Http;

                namespace FunctionApp
                {
                    public class QueueTriggerAndOutput
                    {
                        [Function(""QueueTriggerFunction"")]
                        [QueueOutput(""test-output-dotnet-isolated"")]
                        public string QueueTriggerAndOutputFunction([QueueTrigger(""test-input-dotnet-isolated"")] string message, FunctionContext context)
                        {
                            return message;
                        }
                    }
                }".Replace("'", "\"");

            string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
            string expectedOutput = @"// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Core;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
namespace Microsoft.Azure.Functions.Worker
{
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            var metadataList = new List<IFunctionMetadata>();
            var QueueTriggerFunctionRawBindings = new List<string>();
            var QueueTriggerFunctionreturnBinding = new {
                name = ""$return"",
                type = ""Queue"",
                direction = ""Out"",
                queueName = ""test-output-dotnet-isolated"",
            };
            var QueueTriggerFunctionreturnBindingJSONstring = JsonSerializer.Serialize(QueueTriggerFunctionreturnBinding);
            QueueTriggerFunctionRawBindings.Add(QueueTriggerFunctionreturnBindingJSONstring);
            var QueueTriggerFunctionmessageBinding = new {
                name = ""message"",
                type = ""QueueTrigger"",
                direction = ""In"",
                queueName = ""test-input-dotnet-isolated"",
                dataType = ""String"",
            };
            var QueueTriggerFunctionmessageBindingJSONstring = JsonSerializer.Serialize(QueueTriggerFunctionmessageBinding);
            QueueTriggerFunctionRawBindings.Add(QueueTriggerFunctionmessageBindingJSONstring);
            var QueueTriggerFunction = new DefaultFunctionMetadata
            {
                FunctionId = Guid.NewGuid().ToString(),
                Language = ""dotnet-isolated"",
                Name = ""QueueTriggerFunction"",
                EntryPoint = ""TestProject.QueueTriggerAndOutput.QueueTriggerAndOutputFunction"",
                RawBindings = QueueTriggerFunctionRawBindings,
                ScriptFile = ""TestProject.dll""
            };
            metadataList.Add(QueueTriggerFunction);
            return Task.FromResult(metadataList.ToImmutableArray());
        }
        public enum AuthorizationLevel
        {
            Anonymous,
            User,
            Function,
            System,
            Admin
        }
    }
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}
".Replace("'", "\"");

            await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                referencedExtensionAssemblies,
                inputCode,
                expectedGeneratedFileName,
                expectedOutput);
        }

        [Fact(Skip = "TODO: Find best practices for testing failing source generation and check that diagnostic errors are reported")]
        public async void InvalidFunctionWithIsBatchedTrue()
        {
            string inputCode = @"
                using System;
                using System.Net;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Http;

                namespace FunctionApp
                {
                    public class EventHubStringInput
                    {
                        [Function('StringInputFunction')]
                        public static void StringInputFunction([EventHubTrigger('test', Connection = 'EventHubConnectionAppSetting', IsBatched = true)] string input,
                        FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }
                    }
                }
                ".Replace("'", "\"");

            string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
            string expectedOutput = @"// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Core;
using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
namespace Microsoft.Azure.Functions.Worker
{
    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
    {
        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
        {
            
        }
        public enum AuthorizationLevel
        {
            Anonymous,
            User,
            Function,
            System,
            Admin
        }
    }
    public static class WorkerHostBuilderFunctionMetadataProviderExtension
    {
        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
        {
            builder.ConfigureServices(s => 
            {
                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
            });
            return builder;
        }
    }
}
".Replace("'", "\"");

            await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                referencedExtensionAssemblies,
                inputCode,
                expectedGeneratedFileName,
                expectedOutput);
        }

        [Fact]
        public void FormatStringObjectTest()
        {
            var stringObject = "\"get\"";
            var result = FunctionMetadataProviderGenerator.FormatObject(stringObject);
            // this method should not alter objects that are already strings
            Assert.Equal(stringObject, result);
        }

        [Fact]
        public void FormatEnumObjectTest()
        {
            var enumObjectString = "Enum.GetName(typeof(AuthorizationLevel), 0)";
            var result = FunctionMetadataProviderGenerator.FormatObject(enumObjectString);
            // this method shouldn't alter Enum parsing statements - we want them source generated as a method call, not as a string.
            Assert.Equal(enumObjectString, result);
        }

        [Fact]
        public void FormatNullObjectTest()
        {
            var result = FunctionMetadataProviderGenerator.FormatObject(null);
            Assert.Equal("null", result);
        }

        [Fact]
        public void FormatObjectToGeneratedStringTest()
        {
            var attributeObject = "HttpTrigger";
            var expected = "\"HttpTrigger\"";
            string result = FunctionMetadataProviderGenerator.FormatObject(attributeObject);
            Assert.Equal(expected, result);
        }

        [Fact]
        public void FormatArrayTest()
        {
            var exampleEnumerable = new List<string> { "get", "post" };
            var expected = "new List<string> { \"get\",\"post\" }";
            var result = FunctionMetadataProviderGenerator.FormatArray(exampleEnumerable);
            Assert.Equal(expected, result);
        }
    }
}
