// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System;
using Microsoft.Extensions.Hosting;

namespace Microsoft.Azure.Functions.Worker
{
    /// <summary>
    /// Identifies an <see cref="IHostBuilder"/> extension method generated by Azure functions worker SDK.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method)]
    public sealed class AutoGeneratedHostBuilderConfigureMethodAttribute : Attribute
    {
    }
}
