trigger:
  branches:
    include:
    - main
    - release/*
    - feature/*
  paths:
    include:
    - extensions/Worker.Extensions.Http.AspNetCore/
    - test/extensions/Worker.Extensions.Http.AspNetCore.Tests/

pr:
  branches:
    include:
    - main
    - release/*
    - feature/enhanced-http
  paths:
    include:
    - extensions/Worker.Extensions.Http.AspNetCore/
    - test/extensions/Worker.Extensions.Http.AspNetCore.Tests/

extends:
  template: ../../build/pipelines/templates/extensions-ci.yml
  parameters:
    ExtensionDirectory: extensions/Worker.Extensions.Http.AspNetCore
    Solution: AspNetCore.slnf
    RunExtensionTests: true
