// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System.Reflection;
using Microsoft.Azure.Functions.Worker.Sdk.Generators;
using System.Threading.Tasks;
using Xunit;

namespace Microsoft.Azure.Functions.SdkGeneratorTests
{
    public partial class FunctionMetadataProviderGeneratorTests
    {
        public class RetryOptionsTests
        {
            private readonly Assembly[] _referencedExtensionAssemblies;

            public RetryOptionsTests()
            {
                // load all extensions used in tests (match extensions tested on E2E app? Or include ALL extensions?)
                var abstractionsExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.Abstractions.dll");
                var httpExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.Http.dll");
                var hostingExtension = Assembly.LoadFrom("Microsoft.Extensions.Hosting.dll");
                var diExtension = Assembly.LoadFrom("Microsoft.Extensions.DependencyInjection.dll");
                var hostingAbExtension = Assembly.LoadFrom("Microsoft.Extensions.Hosting.Abstractions.dll");
                var diAbExtension = Assembly.LoadFrom("Microsoft.Extensions.DependencyInjection.Abstractions.dll");
                var cosmosDBExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.CosmosDB.dll");
                var timerExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.Timer.dll");


                _referencedExtensionAssemblies = new[]
                {
                    abstractionsExtension,
                    httpExtension,
                    hostingExtension,
                    hostingAbExtension,
                    diExtension,
                    diAbExtension,
                    timerExtension, 
                    cosmosDBExtension
                };
            }

            [Fact]
            public async Task FixedDelayRetryPopulated_Success()
            {
                // test generating function metadata for a simple HttpTrigger
                string inputCode = """
                using System;
                using Microsoft.Azure.Functions.Worker;

                namespace SampleApp
                {
                    public static class TimerFunction
                    {
                        [Function("TimerFunction")]
                        [FixedDelayRetry(5, "00:00:10")]
                        public static void Run([TimerTrigger("0 */5 * * * *")] TimerInfo timerInfo,
                            FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }
                    }
                }
                """;


                string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
                string expectedOutput = """
                // <auto-generated/>
                using System;
                using System.Collections.Generic;
                using System.Collections.Immutable;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
                using Microsoft.Extensions.DependencyInjection;
                using Microsoft.Extensions.Hosting;
                
                namespace Microsoft.Azure.Functions.Worker
                {
                    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
                    {
                        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
                        {
                            var metadataList = new List<IFunctionMetadata>();
                            var Function0RawBindings = new List<string>();
                            Function0RawBindings.Add(@"{""name"":""timerInfo"",""type"":""TimerTrigger"",""direction"":""In"",""schedule"":""0 */5 * * * *""}");
                
                            var Function0 = new DefaultFunctionMetadata
                            {
                                Language = "dotnet-isolated",
                                Name = "TimerFunction",
                                EntryPoint = "SampleApp.TimerFunction.Run",
                                RawBindings = Function0RawBindings,
                                Retry = new DefaultRetryOptions
                                {
                                    MaxRetryCount = 5,
                                    Strategy = "fixedDelay",
                                    DelayInterval = "00:00:10"
                                },
                                ScriptFile = "TestProject.dll"
                            };
                            metadataList.Add(Function0);
                
                            return Task.FromResult(metadataList.ToImmutableArray());
                        }
                    }
                
                    public static class WorkerHostBuilderFunctionMetadataProviderExtension
                    {
                        ///<summary>
                        /// Adds the GeneratedFunctionMetadataProvider to the service collection.
                        /// During initialization, the worker will return generated function metadata instead of relying on the Azure Functions host for function indexing.
                        ///</summary>
                        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
                        {
                            builder.ConfigureServices(s => 
                            {
                                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
                            });
                            return builder;
                        }
                    }
                }
                """;

                await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                    _referencedExtensionAssemblies,
                    inputCode,
                    expectedGeneratedFileName,
                    expectedOutput);
            }

            [Fact]
            public async Task ExponentialBackoffRetryPopulated_Success()
            {
                // test generating function metadata for a simple HttpTrigger
                string inputCode = """
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Extensions.Logging;

                namespace SampleApp
                {
                    public static class TimerFunction
                    {
                        [Function("TimerFunction")]
                        [FixedDelayRetry(5, "00:00:10")]
                        public static void Run([TimerTrigger("0 */5 * * * *")] TimerInfo timerInfo,
                            FunctionContext context)
                        {
                            var logger = context.GetLogger("TimerFunction");
                            logger.LogInformation($"Function Ran. Next timer schedule = {timerInfo.ScheduleStatus.Next}");
                        }
                    }
                }
                """;

                string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
                string expectedOutput = """
                // <auto-generated/>
                """;

                await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                    _referencedExtensionAssemblies,
                    inputCode,
                    expectedGeneratedFileName,
                    expectedOutput);
            }

            [Fact]
            public async Task RetryUsedWithWrongTrigger_Fails()
            {
                // test generating function metadata for a simple HttpTrigger
                string inputCode = """
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Extensions.Logging;

                namespace SampleApp
                {
                    public static class TimerFunction
                    {
                        [Function("TimerFunction")]
                        [FixedDelayRetry(5, "00:00:10")]
                        public static void Run([TimerTrigger("0 */5 * * * *")] TimerInfo timerInfo,
                            FunctionContext context)
                        {
                            var logger = context.GetLogger("TimerFunction");
                            logger.LogInformation($"Function Ran. Next timer schedule = {timerInfo.ScheduleStatus.Next}");
                        }
                    }
                }
                """;

                string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
                string expectedOutput = """
                // <auto-generated/>
                """;

                await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                    _referencedExtensionAssemblies,
                    inputCode,
                    expectedGeneratedFileName,
                    expectedOutput);
            }
        }
    }
}
