trigger:
  branches:
    include:
    - main
    - release/*
  paths:
    include:
    - extensions/Worker.Extensions.Storage/

pr:
  branches:
    include:
    - main
    - release/*
  paths:
    include:
    - extensions/Worker.Extensions.Storage/

extends:
  template: ../../build/pipelines/templates/extensions-ci.yml
  parameters:
    ExtensionDirectory: extensions/Worker.Extensions.Storage