// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
namespace Microsoft.Azure.Functions.Worker.Sdk.Generators
{
    /// <summary>
    /// Generates a class with a method which has code to call the "Configure" method
    /// of the "IWorkerExtensionStartup" implementations
    /// Also generates an attribute to decorate the class with. 
    /// </summary>

    // Sample code generated (with one extensions particiapating in startup hook)
    // There will be one try-catch block for each extension particiapating in startup hook.

    //[AttributeUsage(AttributeTargets.Class)]
    //public class WorkerExtensionStartupAttribute : Attribute
    //{
    //}
    //[WorkerExtensionStartup]
    //internal class WorkerExtensionStartupRunner
    //{
    //    public void RunStartupForExtensions(IFunctionsWorkerApplicationBuilder builder)
    //    {
    //        try
    //        {
    //            new Microsoft.Azure.Functions.Worker.Extensions.Http.MyHttpExtensionStartup().Configure(builder);
    //        }
    //        catch (Exception ex)
    //        {
    //            Console.WriteLine('Error calling Configure on Microsoft.Azure.Functions.Worker.Extensions.Http.MyHttpExtensionStartup instance.' + ex.ToString());
    //        }
    //    }
    //}

    [Generator]
    public class ExtensionStartupRunnerGenerator : ISourceGenerator
    {
        /// <summary>
        /// The attribute which extension authors will apply on an assembly which contains their startup type.
        /// </summary>
        private string attributeTypeName = "WorkerExtensionStartupAttribute";

        /// <summary>
        /// Fully qualified name of the above "WorkerExtensionStartupAttribute" attribute.
        /// </summary>
        private string attributeTypeFullName = "Microsoft.Azure.Functions.Worker.Core.WorkerExtensionStartupAttribute";

        public void Execute(GeneratorExecutionContext context)
        {
            var startupTypeNames = GetStartupImplementationTypeNames(context);

            if (!startupTypeNames.Any())
            {
                return;
            }

            SourceText sourceText;
            using (var stringWriter = new StringWriter())
            using (var indentedTextWriter = new IndentedTextWriter(stringWriter))
            {
                indentedTextWriter.WriteLine("// <auto-generated/>");
                indentedTextWriter.WriteLine("using System;");
                indentedTextWriter.WriteLine("namespace Microsoft.Azure.Functions.Worker");
                indentedTextWriter.WriteLine("{");
                indentedTextWriter.Indent++;
                WriteStartupDataProviderAttribute(indentedTextWriter);
                WriteStartupRunnerClass(indentedTextWriter, startupTypeNames);
                indentedTextWriter.Indent--;
                indentedTextWriter.WriteLine("}");

                indentedTextWriter.Flush();
                sourceText = SourceText.From(stringWriter.ToString(), encoding: Encoding.UTF8);
            }

            // Add the source code to the compilation
            context.AddSource($"ExtensionStartupRunner.g.cs", sourceText);
        }

        /// <summary>
        /// Gets the type names of extension startup implementations.
        /// </summary>
        private IEnumerable<string> GetStartupImplementationTypeNames(GeneratorExecutionContext context)
        {
            var typeNames = new List<string>();
            // find assemblies with "WorkerExtensionStartupAttribute".
            // Extension authors should decorate their assembly with this attribute if they want to take part in startup.
            var assemblies = context.Compilation.SourceModule.ReferencedAssemblySymbols
                                    .Where(s => s.GetAttributes()
                                                 .Any(a => a.AttributeClass?.Name == attributeTypeName &&
                                                           //Call GetFullName only if class name matches.
                                                           a.AttributeClass.GetFullName() == attributeTypeFullName
                                                        ));

            foreach (var ass in context.Compilation.SourceModule.ReferencedAssemblySymbols)
            {
                var extensionStartupAttribute = ass.GetAttributes()
                                                   .FirstOrDefault(a => a.AttributeClass?.Name == attributeTypeName &&
                                                                        //Call GetFullName only if class name matches.
                                                                        a.AttributeClass.GetFullName() == attributeTypeFullName);
                if (extensionStartupAttribute != null)
                {
                    TypedConstant firstConstructorParam = extensionStartupAttribute.ConstructorArguments[0];
                    if (firstConstructorParam.Value is ITypeSymbol typeSymbol)
                    {
                        var fullTypeName = typeSymbol.ToDisplayString();
                        typeNames.Add(fullTypeName);
                    }
                }
            }

            return typeNames;
        }

        private void WriteStartupDataProviderAttribute(IndentedTextWriter textWriter)
        {
            textWriter.WriteLine("[AttributeUsage(AttributeTargets.Class)]");
            textWriter.WriteLine("public class WorkerExtensionStartupAttribute : Attribute");
            textWriter.WriteLine("{");
            textWriter.WriteLine("}");
        }

        private static void WriteStartupRunnerClass(IndentedTextWriter textWriter, IEnumerable<string> typeNames)
        {
            textWriter.WriteLine("[WorkerExtensionStartup]");
            textWriter.WriteLine("internal class WorkerExtensionStartupRunner");
            textWriter.WriteLine("{");
            textWriter.Indent++;
            textWriter.WriteLine("public void RunStartupForExtensions(IFunctionsWorkerApplicationBuilder builder)");
            textWriter.WriteLine("{");
            textWriter.Indent++;

            foreach (var fullyQualifiedTpeName in typeNames)
            {
                textWriter.WriteLine("try");
                textWriter.WriteLine("{");
                textWriter.Indent++;
                textWriter.WriteLine($"new {fullyQualifiedTpeName}().Configure(builder);");
                textWriter.Indent--;
                textWriter.WriteLine("}");
                textWriter.WriteLine("catch(Exception ex)");
                textWriter.WriteLine("{");
                textWriter.Indent++;
                textWriter.WriteLine($"Console.WriteLine(\"Error calling Configure on {fullyQualifiedTpeName} instance.\"+ex.ToString());");
                textWriter.Indent--;
                textWriter.WriteLine("}");
            }

            textWriter.Indent--;
            textWriter.WriteLine("}");
            textWriter.Indent--;
            textWriter.WriteLine("}");
        }

        public void Initialize(GeneratorInitializationContext context)
        {
        }
    }
}
