// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
namespace Microsoft.Azure.Functions.Worker.Sdk.Generators
{
    /// <summary>
    /// Generates a class with a method to return the startup type names and it's assembly names.
    /// Also generates an attribute to decorate the class with. 
    /// </summary>

    //  [AttributeUsage(AttributeTargets.Class)]
    //  public class ExtensionStartupDataAttribute : Attribute
    //  {
    //  }
    //  [ExtensionStartupData]
    //  internal sealed class ExtensionStartupTypeInfoProvider
    //  {
    //    public IDictionary<string, string> GetStartupTypes()
    //    {
    //        var dict = new Dictionary<string, string>(2);
    //        dict.Add("Microsoft.Azure.Functions.Worker.Extensions.CosmosDB.MyCosmosExtensionStartup", "Microsoft.Azure.Functions.Worker.Extensions.CosmosDB, Version=4.0.1.0, Culture=neutral, PublicKeyToken=551316b6919f366c");
    //        dict.Add("Microsoft.Azure.Functions.Worker.Extensions.Http.MyHttpExtensionStartup", "Microsoft.Azure.Functions.Worker.Extensions.Http, Version=4.0.5.0, Culture=neutral, PublicKeyToken=551316b6919f366c");
    //        return dict;
    //    }
    //  }

    [Generator]
    public class StartupLocatorSourceGenerator : ISourceGenerator
    {
        /// <summary>
        /// The attribute extension authors apply on an assembly which contains their startup type.
        /// </summary>
        private string attributeTypeName = "WorkerExtensionStartupAttribute";

        /// <summary>
        /// Fully qualified name of the above "WorkerExtensionStartupAttribute" attribute.
        /// </summary>
        private string attributeTypeFullName = "Microsoft.Azure.Functions.Worker.Core.WorkerExtensionStartupAttribute";

        public void Execute(GeneratorExecutionContext context)
        {
            var startupTypeNames = GetStartupTypeNames(context);

            if (!startupTypeNames.Any())
            {
                return;
            }

            var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

            SourceText sourceText;
            using (var stringWriter = new StringWriter())
            using (var indentedTextWriter = new IndentedTextWriter(stringWriter))
            {
                indentedTextWriter.WriteLine("// <auto-generated/>");
                indentedTextWriter.WriteLine("using System;");
                indentedTextWriter.WriteLine("using Microsoft.Azure.Functions.Worker;");
                indentedTextWriter.WriteLine($"namespace {mainMethod?.ContainingNamespace?.ToDisplayString() ?? "MyUnitTestNamespace"}");
                indentedTextWriter.WriteLine("{");
                indentedTextWriter.Indent++;
                WriteStartupDataProviderAttribute(indentedTextWriter);
                WriteStartupDataProviderClass(indentedTextWriter, startupTypeNames);
                indentedTextWriter.Indent--;
                indentedTextWriter.WriteLine("}");

                indentedTextWriter.Flush();
                sourceText = SourceText.From(stringWriter.ToString(), encoding: Encoding.UTF8);
            }

            // Add the source code to the compilation
            context.AddSource($"ExtensionStartupRunner.g.cs", sourceText);
        }

        /// <summary>
        /// Gets the type names of extension startup implementations.        
        /// </summary>
        private IEnumerable<string> GetStartupTypeNames(GeneratorExecutionContext context)
        {
            Dictionary<string, string> typeAndAssemblyDict = new();
            var list = new List<string>();
            // find assemblies with "WorkerExtensionStartupAttribute".
            // Extension authors should decorate their assembly with this attribute if they want to take part in startup.
            var assemblies = context.Compilation.SourceModule.ReferencedAssemblySymbols
                                    .Where(s => s.GetAttributes()
                                                 .Any(a => a.AttributeClass?.Name == attributeTypeName &&
                                                           //Call GetFullName only if class name matches.
                                                           a.AttributeClass.GetFullName() == attributeTypeFullName
                                                        ));

            foreach(var ass in context.Compilation.SourceModule.ReferencedAssemblySymbols)
            {
                var extensionStartupAttribute = ass.GetAttributes()
                                                   .FirstOrDefault(a => a.AttributeClass?.Name == attributeTypeName &&
                                                                        //Call GetFullName only if class name matches.
                                                                        a.AttributeClass.GetFullName() == attributeTypeFullName); 
                if (extensionStartupAttribute != null)
                {
                    TypedConstant firstConstructorParam = extensionStartupAttribute.ConstructorArguments[0];
                    if (firstConstructorParam.Value is ITypeSymbol typeSymbol)
                    {
                        var fullTypeName = typeSymbol.ToDisplayString();
                        list.Add(fullTypeName);
                    }
                }
            }

            return list;
        }

        private void WriteStartupDataProviderAttribute(IndentedTextWriter textWriter)
        {
            textWriter.WriteLine("[AttributeUsage(AttributeTargets.Class)]");
            textWriter.WriteLine("public class ExtensionStartupDataAttribute : Attribute");
            textWriter.WriteLine("{");
            textWriter.WriteLine("}");
        }

        private static void WriteStartupDataProviderClass(IndentedTextWriter textWriter, IEnumerable<string> typeNames)
        {
            textWriter.WriteLine("[ExtensionStartupData]");
            textWriter.WriteLine("internal sealed class ExtensionStartupTypeInfoProvider");
            textWriter.WriteLine("{");
            textWriter.Indent++;
            textWriter.WriteLine("public void RunStartup(IFunctionsWorkerApplicationBuilder builder)");
            textWriter.WriteLine("{");
            textWriter.Indent++;

            foreach (var fullyQualifiedTpeName in typeNames)
            {
                textWriter.WriteLine($"new {fullyQualifiedTpeName}().Configure(builder);");
            }
            textWriter.Indent--;
            textWriter.WriteLine("}");
            textWriter.Indent--;
            textWriter.WriteLine("}");
        }

        public void Initialize(GeneratorInitializationContext context)
        {
        }
    }
}
