trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
  paths:
    include:
    - eng/
    - host/src/

# CI only, does not trigger on PRs.
pr: none

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/build.yml@eng
  - template: ci/variables/cfs.yml@eng
  - template: /eng/ci/templates/variables/build.yml@self

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
      ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
        demands:
        - Priority -equals Low

    stages:
    - stage: Build

      jobs:
      - template: /eng/ci/templates/official/jobs/build-host-prelaunch-artifacts.yml@self
      - template: /eng/ci/templates/official/jobs/build-host-artifacts-linux.yml@self
        parameters:
          poolName: 1es-pool-azfunc
      - template: /eng/ci/templates/official/jobs/build-host-artifacts-windows.yml@self

    - stage: Pack
      dependsOn: Build

      jobs:
      - template: /eng/ci/templates/official/jobs/pack-host-artifacts.yml@self
