# This build is used for public PR and CI builds.

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
  paths:
    include:
    - eng/
    - host/src/

pr:
  branches:
    include:
    - main
    - release/*
  paths:
    include:
    - eng/
    - host/src/

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - template: /eng/ci/templates/variables/build.yml@self

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
      ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
        demands:
        - Priority -equals Low

    stages:
    - stage: Build

      jobs:
      - template: /eng/ci/templates/official/jobs/build-host-prelaunch-artifacts.yml@self
      - template: /eng/ci/templates/official/jobs/build-host-artifacts-linux.yml@self
        parameters:
          poolName: 1es-pool-azfunc-public
      # Temp pipeline to just build the net-host (see issue #2521)
      - template: /eng/ci/templates/jobs/build-net-host.yml@self
      # - template: /eng/ci/templates/official/jobs/build-host-artifacts-windows.yml@self
