// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System.Collections.Generic;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Sdk.Generator.Tests;
using Microsoft.Azure.Functions.Worker.Sdk.Generators;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Xunit;

namespace Microsoft.Azure.Functions.Sdk.Generator.FunctionMetadataProvider.Tests
{
    public partial class FunctionMetadataProviderGeneratorTests
    {
        public class EventHubsBindingsTests
        {
            private readonly Assembly[] _referencedExtensionAssemblies;
            private readonly string _usingStringsForInput;

            public EventHubsBindingsTests()
            {
                var abstractionsExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.Abstractions.dll");
                var httpExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.Http.dll");
                var eventHubsExtension = Assembly.LoadFrom("Microsoft.Azure.Functions.Worker.Extensions.EventHubs.dll");
                var hostingExtension = typeof(HostBuilder).Assembly;
                var diExtension = typeof(DefaultServiceProviderFactory).Assembly;
                var hostingAbExtension = typeof(IHost).Assembly;
                var diAbExtension = typeof(IServiceCollection).Assembly;
                _referencedExtensionAssemblies = new[]
                {
                    abstractionsExtension,
                    httpExtension,
                    eventHubsExtension,
                    hostingExtension,
                    hostingAbExtension,
                    diExtension,
                    diAbExtension
                };

                _usingStringsForInput = @"using System;
                using System.Net;
                using System.Linq;
                using System.Text.Json;
                using System.Collections;
                using System.Collections.Concurrent;
                using System.Collections.Generic;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Http;";
            }

            [Theory]
            [InlineData("StringInputFunction", "string", "String")]
            [InlineData("BinaryInputFunction", "byte[]", "Binary")]
            [InlineData("DictionaryInputFunction", "Dictionary<string, string>", "")]
            [InlineData("LookupFunction", "Lookup<string, int>", "")]
            [InlineData("ConcurrentDictionaryInputFunction", "ConcurrentDictionary<string, string>", "")]
            public async Task FunctionsWithIsBatchedFalse(string functionName, string parameterType, string dataType)
            {
                StringBuilder inputCodeBuilder = new StringBuilder();
                inputCodeBuilder.Append(_usingStringsForInput);
                inputCodeBuilder.Append(@"
                namespace FunctionApp
                {
                    public class EventHubsInput
                    {");
                inputCodeBuilder.AppendLine("[Function(\"" + functionName + "\")]");
                inputCodeBuilder.AppendLine("public static void " + functionName + @"([EventHubTrigger(""test"", Connection = ""EventHubConnectionAppSetting"", IsBatched = false)]" + parameterType + " input, \n");
                inputCodeBuilder.Append(@"
                        FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }
                    }
                }");

                string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
                var expectedOutputBuilder = new StringBuilder();
                var rawBindingSuffix = !string.Equals(dataType, "")
                    ? @",""""dataType"""":""""" + dataType + @"""""}"");"
                    : @"}"");";
                expectedOutputBuilder.Append($$"""
                // <auto-generated/>
                using System;
                using System.Collections.Generic;
                using System.Collections.Immutable;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
                using Microsoft.Extensions.DependencyInjection;
                using Microsoft.Extensions.Hosting;

                namespace TestProject
                {
                    /// <summary>
                    /// Custom <see cref="IFunctionMetadataProvider"/> implementation that returns function metadata definitions for the current worker.
                    /// </summary>
                    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
                    {{Constants.GeneratedCodeAttribute}}
                    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
                    {
                        /// <inheritdoc/>
                        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
                        {
                            var metadataList = new List<IFunctionMetadata>();
                            var Function0RawBindings = new List<string>();
                            Function0RawBindings.Add(@"{""name"":""input"",""type"":""eventHubTrigger"",""direction"":""In"",""eventHubName"":""test"",""connection"":""EventHubConnectionAppSetting"",""cardinality"":""One""{{rawBindingSuffix}}

                """);

                expectedOutputBuilder.Append($$"""

                                var Function0 = new DefaultFunctionMetadata
                                {
                                    Language = "dotnet-isolated",
                                    Name = "{{functionName}}",
                                    EntryPoint = "FunctionApp.EventHubsInput.{{functionName}}",
                                    RawBindings = Function0RawBindings,
                                    ScriptFile = "TestProject.dll"
                                };
                                metadataList.Add(Function0);

                                return global::System.Threading.Tasks.Task.FromResult(metadataList.ToImmutableArray());
                            }
                        }

                        /// <summary>
                        /// Extension methods to enable registration of the custom <see cref="IFunctionMetadataProvider"/> implementation generated for the current worker.
                        /// </summary>
                        {{Constants.GeneratedCodeAttribute}}
                        public static class WorkerHostBuilderFunctionMetadataProviderExtension
                        {
                            ///<summary>
                            /// Adds the GeneratedFunctionMetadataProvider to the service collection.
                            /// During initialization, the worker will return generated function metadata instead of relying on the Azure Functions host for function indexing.
                            ///</summary>
                            public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
                            {
                                builder.ConfigureServices(s => 
                                {
                                    s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
                                });
                                return builder;
                            }
                        }
                    }
                    """);

                await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                    _referencedExtensionAssemblies,
                    inputCodeBuilder.ToString(),
                    expectedGeneratedFileName,
                    expectedOutputBuilder.ToString());
            }

            [Theory]
            [InlineData("BinaryArrayInputFunction", "byte[][]", "Binary")]
            [InlineData("StringDoubleArrayInputFunction", "string[][]", "")]
            [InlineData("IntArrayInputFunction", "int[]", "")]
            [InlineData("StringArrayInputFunction", "string[]", "String")]
            [InlineData("StringListInputFunction", "List<string>", "String")]
            [InlineData("BinaryListInputFunction", "List<byte[]>", "Binary")]
            [InlineData("IntListInputFunction", "List<int>", "")]
            [InlineData("HashSetInputFunction", "HashSet<string>", "String")]
            [InlineData("EnumerableBinaryInputFunction", "IEnumerable<byte[]>", "Binary")]
            [InlineData("EnumerableStringInputFunction", "IEnumerable<string>", "String")]
            [InlineData("EnumerableInputFunction", "IEnumerable", "")]
            [InlineData("EnumerableClassInputFunction", "EnumerableTestClass", "")]
            [InlineData("EnumerableGenericClassInputFunction", "EnumerableGenericTestClass", "")]
            public async Task FunctionsWithCardinalityMany(string functionName, string parameterType, string dataType)
            {
                StringBuilder inputCodeBuilder = new StringBuilder();
                inputCodeBuilder.Append(_usingStringsForInput);
                inputCodeBuilder.Append($$"""
                namespace FunctionApp
                {
                    public class EventHubsInput
                    {
                        [Function("{{functionName}}")]
                        public static void {{functionName}}([EventHubTrigger("test", Connection = "EventHubConnectionAppSetting")] {{parameterType}} input, FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }
                    }

                    public class EnumerableTestClass : IEnumerable
                    {
                        public IEnumerator GetEnumerator()
                        {
                            throw new NotImplementedException();
                        }
                    }

                    public class EnumerableGenericTestClass : IEnumerable<int>
                    {
                        public IEnumerator GetEnumerator()
                        {
                            throw new NotImplementedException();
                        }

                        IEnumerator<int> IEnumerable<int>.GetEnumerator()
                        {
                            throw new NotImplementedException();
                        }
                    }
                }
                """);

                string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
                var expectedOutputBuilder = new StringBuilder();

                var rawBindingSuffix = !string.Equals(dataType, "")
                    ? @",""""dataType"""":""""" + dataType + @"""""}"");"
                    : @"}"");";

                expectedOutputBuilder.Append($$"""
                // <auto-generated/>
                using System;
                using System.Collections.Generic;
                using System.Collections.Immutable;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
                using Microsoft.Extensions.DependencyInjection;
                using Microsoft.Extensions.Hosting;

                namespace TestProject
                {
                    /// <summary>
                    /// Custom <see cref="IFunctionMetadataProvider"/> implementation that returns function metadata definitions for the current worker.
                    /// </summary>
                    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
                    {{Constants.GeneratedCodeAttribute}}
                    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
                    {
                        /// <inheritdoc/>
                        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
                        {
                            var metadataList = new List<IFunctionMetadata>();
                            var Function0RawBindings = new List<string>();
                            Function0RawBindings.Add(@"{""name"":""input"",""type"":""eventHubTrigger"",""direction"":""In"",""eventHubName"":""test"",""connection"":""EventHubConnectionAppSetting"",""cardinality"":""Many""{{rawBindingSuffix}}


                """);

                expectedOutputBuilder.Append($$"""
                            var Function0 = new DefaultFunctionMetadata
                            {
                                Language = "dotnet-isolated",
                                Name = "{{functionName}}",
                                EntryPoint = "FunctionApp.EventHubsInput.{{functionName}}",
                                RawBindings = Function0RawBindings,
                                ScriptFile = "TestProject.dll"
                            };
                            metadataList.Add(Function0);

                            return global::System.Threading.Tasks.Task.FromResult(metadataList.ToImmutableArray());
                        }
                    }

                    /// <summary>
                    /// Extension methods to enable registration of the custom <see cref="IFunctionMetadataProvider"/> implementation generated for the current worker.
                    /// </summary>
                    {{Constants.GeneratedCodeAttribute}}
                    public static class WorkerHostBuilderFunctionMetadataProviderExtension
                    {
                        ///<summary>
                        /// Adds the GeneratedFunctionMetadataProvider to the service collection.
                        /// During initialization, the worker will return generated function metadata instead of relying on the Azure Functions host for function indexing.
                        ///</summary>
                        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
                        {
                            builder.ConfigureServices(s => 
                            {
                                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
                            });
                            return builder;
                        }
                    }
                }
                """);

                await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                    _referencedExtensionAssemblies,
                    inputCodeBuilder.ToString(),
                    expectedGeneratedFileName,
                    expectedOutputBuilder.ToString());
            }

            [Theory]
            [InlineData(LanguageVersion.CSharp7_3)]
            [InlineData(LanguageVersion.CSharp8)]
            [InlineData(LanguageVersion.CSharp9)]
            [InlineData(LanguageVersion.CSharp10)]
            [InlineData(LanguageVersion.CSharp11)]
            [InlineData(LanguageVersion.Latest)]
            public async Task EnumerableGenericInputFunction(LanguageVersion languageVersion)
            {
                string inputCode = """
                using System;
                using System.Net;
                using System.Collections.Generic;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Http;
                using System.Linq;
                using System.Threading.Tasks;

                namespace FunctionApp
                {
                    public class EventHubsInput
                    {
                        [Function("EnumerableBinaryInputFunction")]
                        public static void EnumerableBinaryInputFunction<T>([EventHubTrigger("test", Connection = "EventHubConnectionAppSetting")] IEnumerable<T> input,
                            FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }
                    }
                }
                """;

                string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
                string expectedOutput = $$"""
                // <auto-generated/>
                using System;
                using System.Collections.Generic;
                using System.Collections.Immutable;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
                using Microsoft.Extensions.DependencyInjection;
                using Microsoft.Extensions.Hosting;

                namespace TestProject
                {
                    /// <summary>
                    /// Custom <see cref="IFunctionMetadataProvider"/> implementation that returns function metadata definitions for the current worker.
                    /// </summary>
                    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
                    {{Constants.GeneratedCodeAttribute}}
                    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
                    {
                        /// <inheritdoc/>
                        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
                        {
                            var metadataList = new List<IFunctionMetadata>();
                            var Function0RawBindings = new List<string>();
                            Function0RawBindings.Add(@"{""name"":""input"",""type"":""eventHubTrigger"",""direction"":""In"",""eventHubName"":""test"",""connection"":""EventHubConnectionAppSetting"",""cardinality"":""Many""}");

                            var Function0 = new DefaultFunctionMetadata
                            {
                                Language = "dotnet-isolated",
                                Name = "EnumerableBinaryInputFunction",
                                EntryPoint = "FunctionApp.EventHubsInput.EnumerableBinaryInputFunction",
                                RawBindings = Function0RawBindings,
                                ScriptFile = "TestProject.dll"
                            };
                            metadataList.Add(Function0);

                            return global::System.Threading.Tasks.Task.FromResult(metadataList.ToImmutableArray());
                        }
                    }

                    /// <summary>
                    /// Extension methods to enable registration of the custom <see cref="IFunctionMetadataProvider"/> implementation generated for the current worker.
                    /// </summary>
                    {{Constants.GeneratedCodeAttribute}}
                    public static class WorkerHostBuilderFunctionMetadataProviderExtension
                    {
                        ///<summary>
                        /// Adds the GeneratedFunctionMetadataProvider to the service collection.
                        /// During initialization, the worker will return generated function metadata instead of relying on the Azure Functions host for function indexing.
                        ///</summary>
                        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
                        {
                            builder.ConfigureServices(s => 
                            {
                                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
                            });
                            return builder;
                        }
                    }
                }
                """;

                await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                    _referencedExtensionAssemblies,
                    inputCode,
                    expectedGeneratedFileName,
                    expectedOutput,
                    languageVersion: languageVersion);
            }

            [Theory]
            [InlineData(LanguageVersion.CSharp7_3)]
            [InlineData(LanguageVersion.CSharp8)]
            [InlineData(LanguageVersion.CSharp9)]
            [InlineData(LanguageVersion.CSharp10)]
            [InlineData(LanguageVersion.CSharp11)]
            [InlineData(LanguageVersion.Latest)]
            public async Task EnumerableStringClassesAsInputFunctions(LanguageVersion languageVersion)
            {
                string inputCode = """
                using System;
                using System.Net;
                using System.Collections;
                using System.Collections.Generic;
                using Microsoft.Azure.Functions.Worker;
                using System.Linq;
                using System.Threading.Tasks;

                namespace FunctionApp
                {
                    public class EventHubsInput
                    {

                        [Function("EnumerableStringClassInputFunction")]
                        public static void EnumerableStringClassInputFunction([EventHubTrigger("test", Connection = "EventHubConnectionAppSetting")] EnumerableStringTestClass input,
                            FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }

                        [Function("EnumerableNestedStringClassInputFunction")]
                        public static void EnumerableNestedStringClassInputFunction([EventHubTrigger("test", Connection = "EventHubConnectionAppSetting")] EnumerableStringNestedTestClass input,
                        FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }

                        [Function("EnumerableNestedStringGenericClassInputFunction")]
                        public static void EnumerableNestedStringGenericClassInputFunction([EventHubTrigger("test", Connection = "EventHubConnectionAppSetting")] EnumerableStringNestedGenericTestClass<string> input,
                            FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }

                        [Function("EnumerableNestedStringGenericClass2InputFunction")]
                        public static void EnumerableNestedStringGenericClass2InputFunction([EventHubTrigger("test", Connection = "EventHubConnectionAppSetting")] EnumerableStringNestedGenericTestClass2<string, int> input,
                            FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }

                        public class EnumerableStringTestClass : IEnumerable<string>
                        {
                            public IEnumerator GetEnumerator()
                            {
                                throw new NotImplementedException();
                            }

                            IEnumerator<string> IEnumerable<string>.GetEnumerator()
                            {
                                throw new NotImplementedException();
                            }
                        }

                        public class EnumerableStringTestClass<T> : List<T>
                        {
                        }

                        public class EnumerableStringNestedTestClass : EnumerableStringTestClass
                        {
                        }

                        public class EnumerableStringNestedGenericTestClass2<T, V> : EnumerableStringNestedGenericTestClass<T>
                        {
                        }

                        public class EnumerableStringNestedGenericTestClass<TK> : EnumerableStringTestClass<TK>
                        {
                        }
                    }
                }
                """;

                string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
                string expectedOutput = $$"""
                // <auto-generated/>
                using System;
                using System.Collections.Generic;
                using System.Collections.Immutable;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
                using Microsoft.Extensions.DependencyInjection;
                using Microsoft.Extensions.Hosting;

                namespace TestProject
                {
                    /// <summary>
                    /// Custom <see cref="IFunctionMetadataProvider"/> implementation that returns function metadata definitions for the current worker.
                    /// </summary>
                    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
                    {{Constants.GeneratedCodeAttribute}}
                    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
                    {
                        /// <inheritdoc/>
                        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
                        {
                            var metadataList = new List<IFunctionMetadata>();
                            var Function0RawBindings = new List<string>();
                            Function0RawBindings.Add(@"{""name"":""input"",""type"":""eventHubTrigger"",""direction"":""In"",""eventHubName"":""test"",""connection"":""EventHubConnectionAppSetting"",""cardinality"":""Many"",""dataType"":""String""}");

                            var Function0 = new DefaultFunctionMetadata
                            {
                                Language = "dotnet-isolated",
                                Name = "EnumerableStringClassInputFunction",
                                EntryPoint = "FunctionApp.EventHubsInput.EnumerableStringClassInputFunction",
                                RawBindings = Function0RawBindings,
                                ScriptFile = "TestProject.dll"
                            };
                            metadataList.Add(Function0);
                            var Function1RawBindings = new List<string>();
                            Function1RawBindings.Add(@"{""name"":""input"",""type"":""eventHubTrigger"",""direction"":""In"",""eventHubName"":""test"",""connection"":""EventHubConnectionAppSetting"",""cardinality"":""Many"",""dataType"":""String""}");

                            var Function1 = new DefaultFunctionMetadata
                            {
                                Language = "dotnet-isolated",
                                Name = "EnumerableNestedStringClassInputFunction",
                                EntryPoint = "FunctionApp.EventHubsInput.EnumerableNestedStringClassInputFunction",
                                RawBindings = Function1RawBindings,
                                ScriptFile = "TestProject.dll"
                            };
                            metadataList.Add(Function1);
                            var Function2RawBindings = new List<string>();
                            Function2RawBindings.Add(@"{""name"":""input"",""type"":""eventHubTrigger"",""direction"":""In"",""eventHubName"":""test"",""connection"":""EventHubConnectionAppSetting"",""cardinality"":""Many"",""dataType"":""String""}");

                            var Function2 = new DefaultFunctionMetadata
                            {
                                Language = "dotnet-isolated",
                                Name = "EnumerableNestedStringGenericClassInputFunction",
                                EntryPoint = "FunctionApp.EventHubsInput.EnumerableNestedStringGenericClassInputFunction",
                                RawBindings = Function2RawBindings,
                                ScriptFile = "TestProject.dll"
                            };
                            metadataList.Add(Function2);
                            var Function3RawBindings = new List<string>();
                            Function3RawBindings.Add(@"{""name"":""input"",""type"":""eventHubTrigger"",""direction"":""In"",""eventHubName"":""test"",""connection"":""EventHubConnectionAppSetting"",""cardinality"":""Many"",""dataType"":""String""}");

                            var Function3 = new DefaultFunctionMetadata
                            {
                                Language = "dotnet-isolated",
                                Name = "EnumerableNestedStringGenericClass2InputFunction",
                                EntryPoint = "FunctionApp.EventHubsInput.EnumerableNestedStringGenericClass2InputFunction",
                                RawBindings = Function3RawBindings,
                                ScriptFile = "TestProject.dll"
                            };
                            metadataList.Add(Function3);

                            return global::System.Threading.Tasks.Task.FromResult(metadataList.ToImmutableArray());
                        }
                    }

                    /// <summary>
                    /// Extension methods to enable registration of the custom <see cref="IFunctionMetadataProvider"/> implementation generated for the current worker.
                    /// </summary>
                    {{Constants.GeneratedCodeAttribute}}
                    public static class WorkerHostBuilderFunctionMetadataProviderExtension
                    {
                        ///<summary>
                        /// Adds the GeneratedFunctionMetadataProvider to the service collection.
                        /// During initialization, the worker will return generated function metadata instead of relying on the Azure Functions host for function indexing.
                        ///</summary>
                        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
                        {
                            builder.ConfigureServices(s => 
                            {
                                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
                            });
                            return builder;
                        }
                    }
                }
                """;

                await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                    _referencedExtensionAssemblies,
                    inputCode,
                    expectedGeneratedFileName,
                    expectedOutput,
                    languageVersion: languageVersion);
            }

            [Theory]
            [InlineData(LanguageVersion.CSharp7_3)]
            [InlineData(LanguageVersion.CSharp8)]
            [InlineData(LanguageVersion.CSharp9)]
            [InlineData(LanguageVersion.CSharp10)]
            [InlineData(LanguageVersion.CSharp11)]
            [InlineData(LanguageVersion.Latest)]
            public async Task EnumerableBinaryClassesAsInputFunctions(LanguageVersion languageVersion)
            {
                string inputCode = """
                using System;
                using System.Net;
                using System.Collections;
                using System.Collections.Generic;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Http;
                using System.Linq;
                using System.Threading.Tasks;

                namespace FunctionApp
                {
                    public class EventHubsInput
                    {
                        [Function("EnumerableBinaryClassInputFunction")]
                        public static void EnumerableBinaryClassInputFunction([EventHubTrigger("test", Connection = "EventHubConnectionAppSetting")] EnumerableBinaryTestClass input,
                            FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }

                        [Function("EnumerableNestedBinaryClassInputFunction")]
                        public static void EnumerableNestedBinaryClassInputFunction([EventHubTrigger("test", Connection = "EventHubConnectionAppSetting")] EnumerableBinaryNestedTestClass input,
                            FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }

                        public class EnumerableBinaryTestClass : IEnumerable<byte[]>
                        {
                            public IEnumerator GetEnumerator()
                            {
                                throw new NotImplementedException();
                            }

                            IEnumerator<byte[]> IEnumerable<byte[]>.GetEnumerator()
                            {
                                throw new NotImplementedException();
                            }
                        }

                        public class EnumerableBinaryNestedTestClass : EnumerableBinaryTestClass
                        {
                        }
                    }
                }
                """;

                string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
                string expectedOutput = $$"""
                // <auto-generated/>
                using System;
                using System.Collections.Generic;
                using System.Collections.Immutable;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
                using Microsoft.Extensions.DependencyInjection;
                using Microsoft.Extensions.Hosting;

                namespace TestProject
                {
                    /// <summary>
                    /// Custom <see cref="IFunctionMetadataProvider"/> implementation that returns function metadata definitions for the current worker.
                    /// </summary>
                    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
                    {{Constants.GeneratedCodeAttribute}}
                    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
                    {
                        /// <inheritdoc/>
                        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
                        {
                            var metadataList = new List<IFunctionMetadata>();
                            var Function0RawBindings = new List<string>();
                            Function0RawBindings.Add(@"{""name"":""input"",""type"":""eventHubTrigger"",""direction"":""In"",""eventHubName"":""test"",""connection"":""EventHubConnectionAppSetting"",""cardinality"":""Many"",""dataType"":""Binary""}");

                            var Function0 = new DefaultFunctionMetadata
                            {
                                Language = "dotnet-isolated",
                                Name = "EnumerableBinaryClassInputFunction",
                                EntryPoint = "FunctionApp.EventHubsInput.EnumerableBinaryClassInputFunction",
                                RawBindings = Function0RawBindings,
                                ScriptFile = "TestProject.dll"
                            };
                            metadataList.Add(Function0);
                            var Function1RawBindings = new List<string>();
                            Function1RawBindings.Add(@"{""name"":""input"",""type"":""eventHubTrigger"",""direction"":""In"",""eventHubName"":""test"",""connection"":""EventHubConnectionAppSetting"",""cardinality"":""Many"",""dataType"":""Binary""}");

                            var Function1 = new DefaultFunctionMetadata
                            {
                                Language = "dotnet-isolated",
                                Name = "EnumerableNestedBinaryClassInputFunction",
                                EntryPoint = "FunctionApp.EventHubsInput.EnumerableNestedBinaryClassInputFunction",
                                RawBindings = Function1RawBindings,
                                ScriptFile = "TestProject.dll"
                            };
                            metadataList.Add(Function1);

                            return global::System.Threading.Tasks.Task.FromResult(metadataList.ToImmutableArray());
                        }
                    }

                    /// <summary>
                    /// Extension methods to enable registration of the custom <see cref="IFunctionMetadataProvider"/> implementation generated for the current worker.
                    /// </summary>
                    {{Constants.GeneratedCodeAttribute}}
                    public static class WorkerHostBuilderFunctionMetadataProviderExtension
                    {
                        ///<summary>
                        /// Adds the GeneratedFunctionMetadataProvider to the service collection.
                        /// During initialization, the worker will return generated function metadata instead of relying on the Azure Functions host for function indexing.
                        ///</summary>
                        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
                        {
                            builder.ConfigureServices(s => 
                            {
                                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
                            });
                            return builder;
                        }
                    }
                }
                """;

                await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                    _referencedExtensionAssemblies,
                    inputCode,
                    expectedGeneratedFileName,
                    expectedOutput,
                    languageVersion: languageVersion);
            }

            [Theory]
            [InlineData(LanguageVersion.CSharp7_3)]
            [InlineData(LanguageVersion.CSharp8)]
            [InlineData(LanguageVersion.CSharp9)]
            [InlineData(LanguageVersion.CSharp10)]
            [InlineData(LanguageVersion.CSharp11)]
            [InlineData(LanguageVersion.Latest)]
            public async Task PocoInputFunctions(LanguageVersion languageVersion)
            {
                string inputCode = """
                using System;
                using System.Net;
                using System.Collections;
                using System.Collections.Generic;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Http;
                using System.Linq;
                using System.Threading.Tasks;

                namespace FunctionApp
                {
                    public class EventHubsInput
                    {
                        [Function("EnumerablePocoInputFunction")]
                        public static void EnumerablePocoInputFunction<T>([EventHubTrigger("test", Connection = "EventHubConnectionAppSetting")] IEnumerable<Poco> input,
                        FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }

                        [Function("ListPocoInputFunction")]
                        public static void ListPocoInputFunction<T>([EventHubTrigger("test", Connection = "EventHubConnectionAppSetting")] List<Poco> input,
                            FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }

                        public class Poco
                        {
                        }
                    }
                }
                """;

                string expectedGeneratedFileName = $"GeneratedFunctionMetadataProvider.g.cs";
                string expectedOutput = $$"""
                // <auto-generated/>
                using System;
                using System.Collections.Generic;
                using System.Collections.Immutable;
                using System.Text.Json;
                using System.Threading.Tasks;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Core.FunctionMetadata;
                using Microsoft.Extensions.DependencyInjection;
                using Microsoft.Extensions.Hosting;

                namespace TestProject
                {
                    /// <summary>
                    /// Custom <see cref="IFunctionMetadataProvider"/> implementation that returns function metadata definitions for the current worker.
                    /// </summary>
                    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
                    {{Constants.GeneratedCodeAttribute}}
                    public class GeneratedFunctionMetadataProvider : IFunctionMetadataProvider
                    {
                        /// <inheritdoc/>
                        public Task<ImmutableArray<IFunctionMetadata>> GetFunctionMetadataAsync(string directory)
                        {
                            var metadataList = new List<IFunctionMetadata>();
                            var Function0RawBindings = new List<string>();
                            Function0RawBindings.Add(@"{""name"":""input"",""type"":""eventHubTrigger"",""direction"":""In"",""eventHubName"":""test"",""connection"":""EventHubConnectionAppSetting"",""cardinality"":""Many""}");

                            var Function0 = new DefaultFunctionMetadata
                            {
                                Language = "dotnet-isolated",
                                Name = "EnumerablePocoInputFunction",
                                EntryPoint = "FunctionApp.EventHubsInput.EnumerablePocoInputFunction",
                                RawBindings = Function0RawBindings,
                                ScriptFile = "TestProject.dll"
                            };
                            metadataList.Add(Function0);
                            var Function1RawBindings = new List<string>();
                            Function1RawBindings.Add(@"{""name"":""input"",""type"":""eventHubTrigger"",""direction"":""In"",""eventHubName"":""test"",""connection"":""EventHubConnectionAppSetting"",""cardinality"":""Many""}");

                            var Function1 = new DefaultFunctionMetadata
                            {
                                Language = "dotnet-isolated",
                                Name = "ListPocoInputFunction",
                                EntryPoint = "FunctionApp.EventHubsInput.ListPocoInputFunction",
                                RawBindings = Function1RawBindings,
                                ScriptFile = "TestProject.dll"
                            };
                            metadataList.Add(Function1);

                            return global::System.Threading.Tasks.Task.FromResult(metadataList.ToImmutableArray());
                        }
                    }

                    /// <summary>
                    /// Extension methods to enable registration of the custom <see cref="IFunctionMetadataProvider"/> implementation generated for the current worker.
                    /// </summary>
                    {{Constants.GeneratedCodeAttribute}}
                    public static class WorkerHostBuilderFunctionMetadataProviderExtension
                    {
                        ///<summary>
                        /// Adds the GeneratedFunctionMetadataProvider to the service collection.
                        /// During initialization, the worker will return generated function metadata instead of relying on the Azure Functions host for function indexing.
                        ///</summary>
                        public static IHostBuilder ConfigureGeneratedFunctionMetadataProvider(this IHostBuilder builder)
                        {
                            builder.ConfigureServices(s => 
                            {
                                s.AddSingleton<IFunctionMetadataProvider, GeneratedFunctionMetadataProvider>();
                            });
                            return builder;
                        }
                    }
                }
                """;

                await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                    _referencedExtensionAssemblies,
                    inputCode,
                    expectedGeneratedFileName,
                    expectedOutput,
                    languageVersion: languageVersion);
            }

            [Theory]
            [InlineData(LanguageVersion.CSharp7_3)]
            [InlineData(LanguageVersion.CSharp8)]
            [InlineData(LanguageVersion.CSharp9)]
            [InlineData(LanguageVersion.CSharp10)]
            [InlineData(LanguageVersion.CSharp11)]
            [InlineData(LanguageVersion.Latest)]
            public async Task CardinalityManyWithNonIterableInputFails(LanguageVersion languageVersion)
            {
                var inputCode = @"using System;
                using System.Net;
                using System.Collections;
                using System.Collections.Generic;
                using Microsoft.Azure.Functions.Worker;
                using Microsoft.Azure.Functions.Worker.Http;
                using System.Linq;
                using System.Threading.Tasks;

                namespace FunctionApp
                {
                    public class EventHubsInput
                    {
                        [Function(""InvalidEventHubsTrigger"")]
                        public static void InvalidEventHubsTrigger([EventHubTrigger(""test"", Connection = ""EventHubConnectionAppSetting"")] string input,
                            FunctionContext context)
                        {
                            throw new NotImplementedException();
                        }
                    }
                }";

                string? expectedGeneratedFileName = null;
                string? expectedOutput = null;

                var expectedDiagnosticResults = new List<DiagnosticResult>
                {
                    new DiagnosticResult(DiagnosticDescriptors.InvalidCardinality)
                    // these arguments are the values we pass as the message format parameters when creating the DiagnosticDescriptor instance.
                    .WithArguments("input")
                };

                await TestHelpers.RunTestAsync<FunctionMetadataProviderGenerator>(
                    _referencedExtensionAssemblies,
                    inputCode,
                    expectedGeneratedFileName,
                    expectedOutput,
                    expectedDiagnosticResults,
                    languageVersion: languageVersion);
            }
        }
    }
}
