// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System;

namespace Microsoft.Azure.Functions.Worker.Sdk
{
    internal static class Constants
    {
        // Our types
        internal const string BindingType = "Microsoft.Azure.Functions.Worker.Extensions.Abstractions.BindingAttribute";
        internal const string OutputBindingType = "Microsoft.Azure.Functions.Worker.Extensions.Abstractions.OutputBindingAttribute";
        internal const string FunctionNameType = "Microsoft.Azure.Functions.Worker.FunctionAttribute";
        internal const string ExtensionsInformationType = "Microsoft.Azure.Functions.Worker.Extensions.Abstractions.ExtensionInformationAttribute";
        internal const string HttpResponseType = "Microsoft.Azure.Functions.Worker.Http.HttpResponseData";
        internal const string HttpResultAttributeType = "Microsoft.Azure.Functions.Worker.HttpResultAttribute";
        internal const string DefaultValueAttributeType = "Microsoft.Azure.Functions.Worker.Extensions.Abstractions.DefaultValueAttribute";
        internal const string FixedDelayRetryAttributeType = "Microsoft.Azure.Functions.Worker.FixedDelayRetryAttribute";
        internal const string ExponentialBackoffRetryAttributeType = "Microsoft.Azure.Functions.Worker.ExponentialBackoffRetryAttribute";
        internal const string BindingPropertyNameAttributeType = "Microsoft.Azure.Functions.Worker.Extensions.Abstractions.BindingPropertyNameAttribute";
        internal const string SupportsDeferredBindingAttributeType = "Microsoft.Azure.Functions.Worker.Extensions.Abstractions.SupportsDeferredBindingAttribute";
        internal const string InputConverterAttributeType = "Microsoft.Azure.Functions.Worker.Converters.InputConverterAttribute";
        internal const string SupportedTargetTypeAttributeType = "Microsoft.Azure.Functions.Worker.Converters.SupportedTargetTypeAttribute";

        // System types
        internal const string IEnumerableType = "System.Collections.IEnumerable";
        internal const string IEnumerableGenericType = "System.Collections.Generic.IEnumerable`1";
        internal const string IEnumerableOfStringType = "System.Collections.Generic.IEnumerable`1<System.String>";
        internal const string IEnumerableOfBinaryType = "System.Collections.Generic.IEnumerable`1<System.Byte[]>";
        internal const string IEnumerableOfT = "System.Collections.Generic.IEnumerable`1<T>";
        internal const string IEnumerableOfKeyValuePair = "System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<TKey,TValue>>";
        internal const string GenericIEnumerableArgumentName = "T";
        internal const string StringType = "System.String";
        internal const string ByteArrayType = "System.Byte[]";
        internal const string LookupGenericType = "System.Linq.Lookup`2";
        internal const string DictionaryGenericType = "System.Collections.Generic.Dictionary`2";
        internal const string TaskGenericType = "System.Threading.Tasks.Task`1";
        internal const string TaskType = "System.Threading.Tasks.Task";
        internal const string VoidType = "System.Void";
        internal const string ReadOnlyMemoryOfBytes = "System.ReadOnlyMemory`1<System.Byte>";

        internal const string ReturnBindingName = "$return";
        internal const string HttpTriggerBindingType = "httpTrigger";
        internal const string IsBatchedKey = "IsBatched";

        // NetFramework
        internal const string NetCoreApp31 = "netcoreapp3.1";
        internal const string Net60 = "net6.0";
        internal const string NetCoreApp = ".NETCoreApp";
        internal const string NetCoreVersion6 = "v6.0";
        internal const string NetCoreVersion31 = "v3.1";
        internal const string AzureFunctionsVersion3 = "v3";

        // Binding directions
        internal const string OutputBindingDirection = "Out";
        internal const string InputBindingDirection = "In";

        // Binding properties
        internal const string SupportsDeferredBindingProperty = "SupportsDeferredBinding";

        internal readonly static Version AssemblyVersion = typeof(Constants).Assembly.GetName().Version;

        internal readonly static string ExtensionCsProjDisclaimer = $@"<!--
***********************************************************************************************
AUTOGENERATED: DO NOT EDIT this file.

This file is auto-generated by Microsoft.Azure.Functions.Worker.Sdk/{AssemblyVersion}
***********************************************************************************************
-->";

        internal readonly static string ExternalExtensionCsProjDisclaimer = $@"<!--
***********************************************************************************************
AUTOGENERATED: DO NOT EDIT this file.

This file is auto-generated by Microsoft.Azure.Functions.Worker.Sdk/{AssemblyVersion}

To customize the behavior of this project, use the Directory.Build.props and
Directory.Build.targets generated beside this csproj.

WARNING
Changing the build outputs of this project may impact the your function app. Exercise caution.

- DO NOT change the TargetFramework
- DO NOT add custom assemblies to the extensions payload
- AVOID changing packages

Some, but not all, issues that may occur are:

- Assembly load errors
- Missing method errors
- Extension mismatches (missing features, bug fixes, etc)

Azure functions does not support adding custom assemblies to the extensions payload.

See https://github.com/Azure/azure-functions-dotnet-worker/tree/main/samples/ExternalExtensionProject for more information.
***********************************************************************************************
-->";
    }
}
