jobs:

- job: BuildPreJitApp
  displayName: Build Pre-jit placeholder app artifacts

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish Pre-jit placeholder app artifacts
      path: $(Build.ArtifactStagingDirectory)/_preJitAppPackages
      artifact: _preJitAppPackages

  variables:
    targetFrameworks: 'net8.0,net9.0'

  steps:
  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - ${{ each tfm in split(variables.targetFrameworks, ',') }}:
    - task: DotNetCoreCLI@2
      displayName: ${{ tfm }} publish of pre-jit app
      inputs:
        command: publish
        publishWebProjects: false
        zipAfterPublish: false
        modifyOutputPath: false
        arguments: -c Release -o $(Build.ArtifactStagingDirectory)/_preJitAppPackages/${{ replace(tfm, 'net', '') }} -f ${{ tfm }} -p:UseAppHost=false
        projects: PlaceholderApp/FunctionsNetHost.PlaceholderApp.csproj
        workingDirectory: host/src
