jobs:
- job: BuildArtifactsWindows
  displayName: Build Windows Artifacts

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish nuget packages
      path: $(Build.ArtifactStagingDirectory)/NugetPackages
      artifact: NugetPackages

  pool:
    name: 1es-pool-azfunc
    image: 1es-windows-2022
    os: windows

  variables:
    ${{ if and( not(contains(variables['Build.SourceBranch'], '/release/')),  not(startsWith(variables['Build.SourceBranch'], 'refs/tags')) ) }}:
      buildNumberTemp: $(Build.BuildNumber)
    ${{ if or( contains(variables['Build.SourceBranch'], '/release/'), startsWith(variables['Build.SourceBranch'], 'refs/tags') ) }}:
      isReleaseBuildTemp: true
    buildNumber: $[variables.buildNumberTemp]
    isReleaseBuild: $[variables.isReleaseBuildTemp]

  steps:
  - template: /eng/ci/templates/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Build worker solution
    inputs:
      command: custom
      custom: build
      arguments: -p:BuildNumber=$(buildNumber) -c release
      projects: |
        DotNetWorker.sln

  - task: EsrpCodeSigning@2
    displayName: Sign SDK assemblies
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: sdk\sdk\bin\Release
      Pattern: Microsoft.Azure.Functions.Worker.Sdk*.dll
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
              "OpusName": "Microsoft",
              "OpusInfo": "http://www.microsoft.com",
              "FileDigest": "/fd \"SHA256\"",
              "PageHash": "/NPH",
              "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
        ]

  - task: DeleteFiles@1
    displayName: Delete CodeSignSummary files
    inputs:
      contents: '**/CodeSignSummary-*.md'

  - task: EsrpCodeSigning@2
    displayName: Sign SDK Analyzers assemblies
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: sdk\Sdk.Analyzers\bin\Release
      Pattern: Microsoft.Azure.Functions.Worker.Sdk*.dll
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
              "OpusName": "Microsoft",
              "OpusInfo": "http://www.microsoft.com",
              "FileDigest": "/fd \"SHA256\"",
              "PageHash": "/NPH",
              "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
        ]

  - task: DeleteFiles@1
    displayName: Delete CodeSignSummary files
    inputs:
      contents: '**/CodeSignSummary-*.md'

  - task: EsrpCodeSigning@2
    displayName: Sign DotNetWorker assemblies
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: src
      Pattern: Microsoft.Azure.Functions.Worker*.dll
      signConfigType: inlineSignParams
      inlineOperation: |
        [
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
              "OpusName": "Microsoft",
              "OpusInfo": "http://www.microsoft.com",
              "FileDigest": "/fd \"SHA256\"",
              "PageHash": "/NPH",
              "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolVerify",
            "Parameters": {},
            "ToolName": "sign",
            "ToolVersion": "1.0"
          }
        ]

  - task: DeleteFiles@1
    displayName: Delete CodeSignSummary files
    inputs:
      contents: '**/CodeSignSummary-*.md'

  - task: DotNetCoreCLI@2
    displayName: Pack SDK
    inputs:
      command: custom
      custom: pack
      arguments: '--no-build -c release -p:PackageOutputPath=$(System.DefaultWorkingDirectory)\packages -p:BuildNumber=$(buildNumber)'
      projects: |
        **/Sdk.csproj

  - task: DotNetCoreCLI@2
    displayName: Pack DotNetWorker
    inputs:
      command: custom
      custom: pack
      arguments: '--no-build -c release -p:PackageOutputPath=$(System.DefaultWorkingDirectory)\packages -p:BuildNumber=$(buildNumber)'
      projects: |
        **/DotNetWorker.csproj

  - task: EsrpCodeSigning@2
    displayName: Sign nuget packages
    inputs:
      ConnectedServiceName: ESRP Service-internal
      FolderPath: out/pkg/release
      Pattern: Microsoft.Azure.Functions.Worker*.nupkg
      signConfigType: inlineSignParams
      inlineOperation: |
        [
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetSign",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            },
            {
              "KeyCode": "CP-401405",
              "OperationCode": "NuGetVerify",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            }
        ]

  - task: DeleteFiles@1
    displayName: Delete CodeSignSummary files
    inputs:
      contents: '**/CodeSignSummary-*.md'

  - task: CopyFiles@2
    inputs:
      SourceFolder: out/pkg/release
      Contents: '**/*.nupkg'
      TargetFolder: $(Build.ArtifactStagingDirectory)/NugetPackages
