parameters:
  - name: Projects
    type: object
    default: []

jobs:

- job: BuildArtifacts
  displayName: Build artifacts

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish nuget packages
      path: $(Build.ArtifactStagingDirectory)/NugetPackages
      artifact: NugetPackages

  variables:
    ${{ if and(not(contains(variables['Build.SourceBranch'], '/release/')), not(startsWith(variables['Build.SourceBranch'], 'refs/tags'))) }}:
      buildNumberTemp: $(Build.BuildNumber)
    buildNumber: $[variables.buildNumberTemp]

  steps:
  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - ${{ if not(eq(length(parameters.Projects), 0)) }}:
    - ${{ each Project in parameters.Projects }}:
      - template: /eng/ci/templates/steps/build-extension-project.yml@self
        parameters:
          ExtensionProjectName: ${{ Project }}
