parameters:
  name: SkipPublish
  type: boolean
  default: false

jobs:

- job: BuildFunctionsNetHostWindows
  displayName: '[Windows] Build FunctionsNetHost'

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      condition: eq(variables['SkipPublish'], false)
      displayName: Publish FunctionsNetHost packages
      path: $(Build.ArtifactStagingDirectory)/_functionsNetHostPackagesWindows
      artifact: _functionsNetHostPackagesWindows

  steps:
  - task: UseDotNet@2
    displayName: Install .NET SDK from global.json
    inputs:
      useGlobalJson: true

  - task: DotnetCoreCLI@2
    displayName: Dotnet Publish
    inputs:
      command: publish
      publishWebProjects: false
      zipAfterPublish: false
      arguments: -c Release -r win-x64 -o $(Build.SourcesDirectory)/pkg_output/windows
      workingDirectory: $(Build.SourcesDirectory)/host/src/FunctionsNetHost

  - task: CopyFiles@2
    displayName: Copy files
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/pkg_output/windows
      # Publish output will include many other files. We only need FunctionsNetHost.exe, pdb & nethost.dll
      Contents: |
        FunctionsNetHost.exe
        FunctionsNetHost.pdb
        nethost.dll
      TargetFolder: $(Build.ArtifactStagingDirectory)/_functionsNetHostPackagesWindows
