jobs:

- job: BuildPreJitApp
  displayName: Build Pre-jit placeholder app artifacts

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish Pre-jit placeholder app artifacts
      path: $(Build.ArtifactStagingDirectory)/_preJitAppPackages
      artifact: _preJitAppPackages

  variables:
    targetFrameworks: 'net9.0'

  steps:
  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - script: |
      echo "Available .NET SDKs:"
      dotnet --list-sdks
    displayName: 'List available .NET SDKs'

  - task: DotNetCoreCLI@2
    displayName: 'Restore pre-jit placeholderapp'
    inputs:
      command: build
      projects: host/src/PlaceholderApp/FunctionsNetHost.PlaceholderApp.csproj
      arguments: -f net9.0

  - ${{ each tfm in split(variables.targetFrameworks, ',') }}:
    - task: DotNetCoreCLI@2
      displayName: ${{ tfm }} publish of pre-jit app
      inputs:
        command: publish
        publishWebProjects: false
        zipAfterPublish: false
        modifyOutputPath: false
        arguments: -c Release -o $(Build.ArtifactStagingDirectory)/_preJitAppPackages/9.0 -f net9.0 -p:UseAppHost=false
        projects: host/src/PlaceholderApp/FunctionsNetHost.PlaceholderApp.csproj
