jobs:

- job: PackArtifacts
  displayName: Pack artifacts

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish nuget packages
      path: $(Build.ArtifactStagingDirectory)/NugetPackages
      artifact: NugetPackages

  steps:
  - task: UseDotNet@2
    displayName: Install .NET SDK from global.json
    inputs:
      useGlobalJson: true

  - task: DownloadPipelineArtifact@2
    displayName: Download prelaunch artifacts
    inputs:
      artifactName: _preLaunchAppPackages
      path: $(Build.SourcesDirectory)/host/dist/portable/prelaunchapps

  - task: DownloadPipelineArtifact@2
    displayName: Download prejit artifacts
    inputs:
      artifactName: _preJitAppPackages
      path: $(Build.SourcesDirectory)/host/dist/portable/prejit-placeholder-app

  - task: DownloadPipelineArtifact@2
    displayName: Download host artifacts - linux
    inputs:
      artifactName: _functionsNetHostPackagesLinux
      path: $(Build.SourcesDirectory)/host/dist/linux

  - task: DownloadPipelineArtifact@2
    displayName: Download host artifacts - windows
    inputs:
      artifactName: _functionsNetHostPackagesWindows
      path: $(Build.SourcesDirectory)/host/dist/windows

  - task: NuGetCommand@2
    displayName: Nuget pack
    inputs:
      command: pack
      packagesToPack: $(Build.SourcesDirectory)/host/tools/build/Microsoft.Azure.Functions.DotnetIsolatedNativeHost.nuspec
      versioningScheme: off
      packDestination: $(Build.ArtifactStagingDirectory)/NugetPackages
      basePath: $(Build.SourcesDirectory)/host/tools/build
