jobs:
- job: RunIntegrationTests
  displayName: Run Integration Tests

  pool:
    name: 1es-pool-azfunc
    image: 1es-windows-2022
    os: windows

  variables:
    IsReleaseBranch: $[contains(variables['Build.SourceBranch'], 'release/')]

  steps:
  - task: NuGetAuthenticate@1
    displayName: NuGet Authenticate

  - pwsh: . "tools/start-emulators.ps1" -NoWait
    displayName: "Start emulators (NoWait)"

  - template: /eng/ci/templates/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Build DotNetWorker
    inputs:
      command: build
      projects: DotNetWorker.sln

  - pwsh: |
      $useIntegrationTestingCoreTools = $null
      if (-not ([bool]::TryParse($env:USECORETOOLSBUILDFROMINTEGRATIONTESTS, [ref] $useIntegrationTestingCoreTools)))
      {
        throw "UseCoreToolsBuildFromIntegrationTests can only be set to True or False. Current value is set to $env:USECORETOOLSBUILDFROMINTEGRATIONTESTS"
      }
      ./setup-e2e-tests.ps1 -DotnetVersion 'net7' `
                            -UseCoreToolsBuildFromIntegrationTests:$useIntegrationTestingCoreTools `
                            -SkipBuildOnPack
    displayName: "Setup E2E tests - Net7"

  - task: DotNetCoreCLI@2
    displayName: E2E Tests - NET 7
    inputs:
      command: test
      testRunTitle: E2E Tests
      arguments: -v n --no-build
      projects: |
        **\E2ETests.csproj
        **\SdkE2ETests.csproj

  - pwsh: |
      $useIntegrationTestingCoreTools = $null
      if (-not ([bool]::TryParse($env:USECORETOOLSBUILDFROMINTEGRATIONTESTS, [ref] $useIntegrationTestingCoreTools)))
      {
        throw "UseCoreToolsBuildFromIntegrationTests can only be set to True or False. Current value is set to $env:USECORETOOLSBUILDFROMINTEGRATIONTESTS"
      }
      ./setup-e2e-tests.ps1 -DotnetVersion 'netfx' `
                            -UseCoreToolsBuildFromIntegrationTests:$useIntegrationTestingCoreTools `
                            -SkipBuildOnPack
    displayName: "Setup E2E tests - NetFramework"

  - task: DotNetCoreCLI@2
    displayName: E2E Tests - NET Framework
    inputs:
      command: test
      testRunTitle: E2E Tests
      arguments: -v n --no-build
      projects: |
        **\E2ETests.csproj
        **\SdkE2ETests.csproj
