trigger:
  branches:
    include:
    # Keep this set limited as appropriate (don't mirror individual user branches).
    - main
    - release/*
    - feature/*
  tags:
    include:
    - "*"

resources:
  repositories:
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
- template: ci/variables/cfs.yml@eng

extends:
  template: ci/code-mirror.yml@eng
