parameters:
- name: forceOfficial # this is used for testing the official CI from non-official branches.
  displayName: Use official templates for non-official branches
  type: boolean
  default: false
- name: runTests
  displayName: Run tests (ignored for official branches)
  type: boolean
  default: true
- name: signFiles
  displayName: Sign files (ignored for official branches)
  type: boolean
  default: false

trigger:
  batch: true
  branches:
    include:
    - dev
    - in-proc
    - release/*
    - internal/release/*

schedules:
# Ensure we build nightly to catch any new CVEs and report SDL often.
- cron: "0 0 * * *"
  displayName: Nightly Build
  branches:
    include:
    - dev
    - in-proc
  always: true

# CI only, does not trigger on PRs.
pr: none

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
- template: /eng/ci/templates/variables/build.yml@self
- template: /ci/variables/cfs.yml@eng
- name: OfficialBranch
  value: ${{ or(eq(variables['Build.SourceBranch'], 'refs/heads/dev'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/internal/release/')) }}
- name: SignFiles # variable for access in other templates
  value: ${{ or(eq(variables.OfficialBranch, true), eq(parameters.signFiles, true)) }}
- name: '1ESTemplate'
  # force official to be true if an official branch. Otherwise respect the official parameter.
  ${{ if or(eq(variables.OfficialBranch, true), eq(parameters.forceOfficial, true)) }}:
    value: 'v1/1ES.Official.PipelineTemplate.yml@1es'
  ${{ else }}:
    value: 'v1/1ES.Unofficial.PipelineTemplate.yml@1es'

extends:
  template: ${{ variables['1ESTemplate'] }}
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
        # Move codeql for source languages to source analysis stage
        runSourceLanguagesInSourceAnalysis: true
      spotBugs:
        enabled: false # Explicitly disabling as our JavaWorker package causes this to light up and subsequently fail.

    stages:
    - stage: Build

      jobs:
      - template: /eng/ci/templates/official/jobs/build-artifacts-windows.yml@self
      - template: /eng/ci/templates/official/jobs/build-artifacts-linux.yml@self

    # tests are always ran for official branches
    - stage: Test
      condition: ${{ or(eq(variables.OfficialBranch, true), eq(parameters.runTests, true)) }}
      dependsOn: ''

      jobs:
      - template: /eng/ci/templates/jobs/run-unit-tests.yml@self
      - template: /eng/ci/templates/official/jobs/run-non-e2e-tests.yml@self
      - template: /eng/ci/templates/official/jobs/run-integration-tests.yml@self
