# Runtime parameters (visible in UI)
parameters:
- name: UseCoreToolsBuildFromIntegrationTests
  displayName: UseCoreToolsBuildFromIntegrationTests
  type: boolean
  default: false
- name: CORE_TOOLS_URL
  displayName: CORE_TOOLS_URL
  type: string
  default: ' '
- name: CORE_TOOLS_URL_LINUX
  displayName: CORE_TOOLS_URL_LINUX
  type: string
  default: ' '
- name: release
  type: boolean
  default: false

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*

# CI only, does not trigger on PRs.
pr: none

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/build.yml@eng
  - template: ci/variables/cfs.yml@eng
  - template: /eng/ci/templates/variables/build.yml@self
  - name: UseCoreToolsBuildFromIntegrationTests
    value: ${{ parameters.UseCoreToolsBuildFromIntegrationTests }}

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-22.04
      os: linux
    sdl:
      sourceAnalysisPool:
        name: 1es-pool-azfunc
        image: 1es-windows-2022
        os: windows

    stages:
    - stage: Build
      jobs:
      - template: /eng/ci/templates/official/jobs/build-artifacts.yml@self

    - stage: Test
      dependsOn: [] # allows you to run stages in parallel

      jobs:
      - template: /eng/ci/templates/jobs/run-unit-tests.yml@self
        parameters:
          PoolName: 1es-pool-azfunc
      - template: /eng/ci/templates/jobs/run-integration-tests-windows.yml@self
        parameters:
          PoolName: 1es-pool-azfunc
      - template: /eng/ci/templates/jobs/run-integration-tests-linux.yml@self
        parameters:
          PoolName: 1es-pool-azfunc

    - ${{ if eq(parameters.release, true) }}:
      - stage: Release
        dependsOn:
          - Build
          - Test
        jobs:
        - template: /eng/ci/templates/official/jobs/release-package.yml@self
          parameters:
            stagingFeed: public/jviau-testing
            artifact: NugetPackages
            targetFolder: worker/test
            isProduction: false
