trigger:
  batch: true
  branches:
    include:
    - dev
    - in-proc
    - release/4.*
    - release/in-proc

# CI only, does not trigger on PRs.
pr: none

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: /eng/ci/templates/variables/build.yml@self
  - template: /ci/variables/cfs.yml@eng
  - name: buildNumber
    value: $[ counter('build', 23000) ] # 23000 selected to be ahead of current host build

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows

    sdl:
      spotBugs:
        enabled: false # Explicitly disabling as our JavaWorker package causes this to light up and subsequently fail.

    stages:
    - stage: Build

      jobs:
      - template: /eng/ci/templates/official/jobs/build-artifacts-windows.yml@self
      - template: /eng/ci/templates/official/jobs/build-artifacts-linux.yml@self

    - stage: Test
      dependsOn: ''

      jobs:
      - template: /eng/ci/templates/jobs/run-unit-tests.yml@self
      - template: /eng/ci/templates/official/jobs/run-non-e2e-tests.yml@self
      - template: /eng/ci/templates/official/jobs/run-integration-tests.yml@self
