# This build is used for public PR and CI builds.

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - feature/*
  paths:
    include:
    - sdk/
    - src/

pr:
  branches:
    include:
    - main
    - release/*
    - feature/*
  paths:
    include:
    - eng/
    - extensions/
    - samples/FunctionApp
    - sdk/
    - src/
    - test/DotNetWorkerTests
    - test/Worker.Extensions.Tests
    - test/E2ETests
    - test/TestUtility
    - tools/


resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - template: /eng/ci/templates/variables/build.yml@self

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-ubuntu-22.04
      os: linux
    sdl:
      sourceAnalysisPool:
        name: 1es-pool-azfunc-public
        image: 1es-windows-2022
        os: windows

    stages:
    - stage: Test

      jobs:
      - template: /eng/ci/templates/jobs/run-unit-tests.yml@self
        parameters:
          PoolName: 1es-pool-azfunc-public
      - template: /eng/ci/templates/jobs/run-integration-tests-windows.yml@self
        parameters:
          PoolName: 1es-pool-azfunc-public
      - template: /eng/ci/templates/jobs/run-integration-tests-linux.yml@self
        parameters:
          PoolName: 1es-pool-azfunc-public
