# This build is used for public PR and CI builds.

# Runtime parameters (visible in UI)
parameters:
- name: UseCoreToolsBuildFromIntegrationTests
  displayName: UseCoreToolsBuildFromIntegrationTests
  type: boolean
  default: false
- name: CORE_TOOLS_URL
  displayName: CORE_TOOLS_URL
  type: string
  default: ' '
- name: CORE_TOOLS_URL_LINUX
  displayName: CORE_TOOLS_URL_LINUX
  type: string
  default: ' '

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - feature/*

pr:
  branches:
    include:
    - main
    - release/*
    - feature/*

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - template: /eng/ci/templates/variables/build.yml@self
  - name: UseCoreToolsBuildFromIntegrationTests
    value: ${{ parameters.UseCoreToolsBuildFromIntegrationTests }}

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-ubuntu-22.04
      os: linux
      ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
        demands:
        - Priority -equals Low
    sdl:
      sourceAnalysisPool:
        name: 1es-pool-azfunc-public
        image: 1es-windows-2022
        os: windows

    settings:
      # PR's from forks do not have sufficient permissions to set tags.
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}

    stages:
    - stage: Core

      jobs:
      - template: /eng/ci/templates/jobs/run-unit-tests.yml@self
        parameters:
          poolName: 1es-pool-azfunc-public
      - template: /eng/ci/templates/jobs/run-integration-tests-windows.yml@self
        parameters:
          poolName: 1es-pool-azfunc-public
      - template: /eng/ci/templates/jobs/run-integration-tests-linux.yml@self
        parameters:
          poolName: 1es-pool-azfunc-public

    - stage: Extensions

      jobs:
      - job: Build
        steps:
        - template: /eng/ci/templates/steps/build.yml@self
          parameters:
            project: DotNetWorker.Extensions.sln
