jobs:

- job: BuildFunctionsNetHostW
  displayName: '[Windows] Build FunctionsNetHost'

  steps:
  - template: /eng/ci/templates/steps/install-dotnet.yml

  - task: DotnetCoreCLI@2
    displayName: Dotnet build
    inputs:
      command: build
      workingDirectory: $(Build.SourcesDirectory)/host/src/FunctionsNetHost
