parameters:
  - name: ExtensionProjectName
    type: string
  - name: HasOwnTestProject
    type: boolean
    default: false

jobs:

- job: RunTests
  displayName: 'Run tests'

  pool:
    name: 1es-pool-azfunc
    image: 1es-ubuntu-22.04
    os: linux

  steps:

  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - ${{ if eq(parameters.HasOwnTestProject, true) }}:
    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: test
        arguments: -v n
        projects: |
          **/${{ parameters.ExtensionProjectName }}.Tests.csproj

  - ${{ if eq(parameters.HasOwnTestProject, false) }}:
    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: test
        arguments: -v n
        projects: |
          **/Worker.Extensions.Tests.csproj
