parameters:
  name: PoolName
  type: string

jobs:
- job: RunIntegrationTests_Linux
  displayName: 'Run integration tests - linux'

  pool:
    name: ${{ parameters.PoolName }}
    image: 1es-ubuntu-22.04
    os: linux
    ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
      demands:
      - Priority -equals Low

  variables:
    test_projects: |
      **/E2ETests.csproj

  steps:

  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Build DotNetWorker
    inputs:
      command: build
      arguments: '-c Release'
      projects: $(test_projects)

  - template: /eng/ci/templates/steps/setup-e2e-tests.yml@self
    parameters:
      DotnetVersion: 'net8'
      UseCoreToolsBuild: $(UseCoreToolsBuildFromIntegrationTests)
      SkipCosmosDBEmulator: true
      SkipBuildOnPack: true

  - task: DotNetCoreCLI@2
    displayName: 'Run E2E tests'
    inputs:
      command: 'test'
      arguments: '--no-build -c Release --filter "FullyQualifiedName~HttpTrigger"' # only run http tests to avoid emulators on Linux
      projects: $(test_projects)
