jobs:
- job: RunIntegrationTests_Windows
  displayName: '[Windows] Run Integration Tests'

  strategy:
    matrix:
      net7:
        dotnetVersion: net7
      netFx:
        dotnetVersion: netfx

  pool:
    name: 1es-pool-azfunc
    image: 1es-windows-2022
    os: windows

  steps:

  - pwsh: . "tools/start-emulators.ps1" -NoWait
    displayName: "Start emulators (NoWait)"

  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Build DotNetWorker
    inputs:
      command: build
      arguments: '-c Release'
      projects: DotNetWorker.sln

  - template: /eng/ci/templates/steps/setup-e2e-tests.yml@self
    parameters:
      UseCoreToolsBuildFromIntegrationTests: $(UseCoreToolsBuildFromIntegrationTests)
      DotnetVersion: $(dotnetVersion)

  - task: DotNetCoreCLI@2
    displayName: 'Run E2E Tests'
    inputs:
      command: test
      arguments: -v n --no-build -c Release
      projects: |
        **\E2ETests.csproj
        **\SdkE2ETests.csproj
