jobs:
- job: RunUnitTests
  displayName: Run Unit Tests

  pool:
    name: 1es-pool-azfunc
    image: 1es-windows-2022
    os: windows
  steps:
  - task: NuGetAuthenticate@1
    displayName: NuGet Authenticate

  - template: /eng/ci/templates/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Unit Tests
    inputs:
      command: test
      testRunTitle: Unit Tests
      arguments: -v n
      projects: |
        **\DotNetWorker.Opentelemetry.Tests.csproj
        **\DotNetWorkerTests.csproj
        **\SdkTests.csproj
        **\Sdk.Analyzers.Tests.csproj
        **\Sdk.Generatior.Tests.csproj
        **\Worker.ApplicationInsights.Tests.csproj
        **\Worker.Extensions.Http.AspNetCore.Tests.csproj
        **\Worker.Extensions.Rpc.Tests.csproj
        **\Worker.Extensions.Shared.Tests.csproj
        **\Worker.Extensions.SignalRService.Tests.csproj
        **\Worker.Extensions.Tests.csproj
