parameters:
- name: poolName
  type: string

jobs:
- job: RunUnitTests
  displayName: 'Run unit tests -'

  strategy:
    matrix:
      linux:
        imageName: '1es-ubuntu-22.04'
        osName: 'linux'
      windows:
        imageName: '1es-windows-2022'
        osName: 'windows'

  pool:
    name: ${{ parameters.poolName }}
    image: $(imageName)
    os: $(osName)
    ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
      demands:
      - Priority -equals Low

  steps:

  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Run Tests
    inputs:
      command: test
      arguments: -v n
      projects: |
        **/DotNetWorker.Tests.csproj
        **/DotNetWorker.ApplicationInsights.Tests.csproj
        **/DotNetWorker.OpenTelemetry.Tests.csproj
        **/Sdk.Analyzers.Tests.csproj
        **/Sdk.Generator.Tests.csproj
        **/Worker.Extensions.Http.AspNetCore.Tests.csproj
        **/Worker.Extensions.Rpc.Tests.csproj
        **/Worker.Extensions.Shared.Tests.csproj
        **/Worker.Extensions.SignalRService.Tests.csproj
        **/Worker.Extensions.Tests.csproj
