jobs:
- job: RunUnitTests_Windows
  displayName: '[Windows] Run Unit Tests'

  pool:
    name: 1es-pool-azfunc
    image: 1es-windows-2022
    os: windows

  steps:
  - task: NuGetAuthenticate@1
    displayName: NuGet Authenticate

  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - template: /eng/ci/templates/steps/run-unit-tests.yml@self
