parameters:
  name: PoolName
  type: string

jobs:
- job: RunIntegrationTests_Linux
  displayName: 'Run integration tests - linux'

  pool:
    name: ${{ parameters.PoolName }}
    image: 1es-ubuntu-22.04
    os: linux

  steps:

  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Build DotNetWorker
    inputs:
      command: build
      arguments: '-c Release'
      projects: |
        DotNetWorker.sln
        DotNetWorker.Extensions.sln

  - template: /eng/ci/templates/steps/setup-e2e-tests.yml@self
    parameters:
      DotnetVersion: 'net8'
      UseCoreToolsBuild: $(UseCoreToolsBuildFromIntegrationTests)
      SkipCosmosDBEmulator: true
      SkipBuildOnPack: true
      CoreToolsUrl: https://cdn.functions.azure.com/public/4.0.194/Azure.Functions.Cli.linux-x64.4.0.7030.zip

  - task: DotNetCoreCLI@2
    displayName: 'Run E2E tests'
    inputs:
      command: 'test'
      arguments: '--no-build -c Release --filter "FullyQualifiedName~HttpTrigger"' # only run http tests to avoid emulators on Linux
      projects: |
        test/**/*Tests.csproj
