parameters:
- name: poolName
  type: string

jobs:
- job: RunIntegrationTests_Windows
  displayName: 'Run integration tests - windows -'

  strategy:
    matrix:
      net8:
        dotnetVersion: 'net8'
      netfx:
        dotnetVersion: 'netfx'

  pool:
    name: ${{ parameters.poolName }}
    image: 1es-windows-2022
    os: windows
    ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
      demands:
      - Priority -equals Low

  variables:
    test_projects: |
      **/E2ETests.csproj
      **/Sdk.E2ETests.csproj

  steps:

  - pwsh: . "tools/start-emulators.ps1" -NoWait
    displayName: "Start emulators (NoWait)"

  - template: /eng/ci/templates/steps/install-dotnet.yml@self

  - task: DotNetCoreCLI@2
    displayName: Build DotNetWorker
    inputs:
      command: build
      arguments: '-c Release'
      projects: $(test_projects)

  - template: /eng/ci/templates/steps/setup-e2e-tests.yml@self
    parameters:
      DotnetVersion: $(dotnetVersion)
      UseCoreToolsBuild: $(UseCoreToolsBuildFromIntegrationTests)
      SkipBuildOnPack: true

  - task: DotNetCoreCLI@2
    displayName: 'Run E2E Tests'
    inputs:
      command: test
      arguments: -v n --no-build -c Release
      projects: $(test_projects)
    env:
      DOTNET_VERSION: $(dotnetVersion)
