// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System.Globalization;
using System.IO.Abstractions;
using System.Text;
using System.Xml;
using Microsoft.Build.Framework;
using NuGet.Frameworks;
using NuGet.ProjectModel;

namespace Azure.Functions.Sdk.Tasks.Extensions;

public class WriteExtensionProject(IFileSystem fileSystem, TimeProvider time)
    : Microsoft.Build.Utilities.Task
{
    // Has empty new-lines to work with XmlWriter.WriteComment.
    private const string Disclaimer =
        """

        <autogenerated>
          This file is auto-generated by a tool.

          Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
          Generated at: {0:u}; Packages hash: {1}
        </autogenerated>

        """;

    private static readonly XmlWriterSettings _xmlSettings = new()
    {
        Encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
        Indent = true,
        IndentChars = "  ",
        NewLineChars = "\n",
        NewLineHandling = NewLineHandling.Replace,
        OmitXmlDeclaration = true,
    };

    private readonly IFileSystem _fileSystem = Throw.IfNull(fileSystem);
    private readonly TimeProvider _time = Throw.IfNull(time);

    public WriteExtensionProject()
        : this(new FileSystem(), TimeProvider.System)
    {
    }

    [Required]
    public ITaskItem[] Packages { get; set; } = [];

    [Required]
    public ITaskItem[] Projects { get; set; } = [];

    public override bool Execute()
    {
        static bool IsTfmMatch(NuGetFramework left, string right)
        {
            // TFMs can be specified in different formats (e.g. net8.0 vs net80), so we need to normalize them before comparing.
            NuGetFramework rightFramework = NuGetFramework.Parse(right);
            return left.Equals(rightFramework);
        }

        Dictionary<Project, ITaskItem[]> packagesByTfm = [];
        foreach (ITaskItem projectItem in Projects)
        {
            Project project = Project.Create(projectItem);
            packagesByTfm[project] = [.. Packages.Where(p => IsTfmMatch(project.Framework, p.TargetFramework))];
        }

        bool success = true;
        foreach (KeyValuePair<Project, ITaskItem[]> kvp in packagesByTfm)
        {
            if (!Execute(kvp.Key, kvp.Value))
            {
                success = false;
            }
        }

        return success;
    }

    private bool Execute(Project project, IEnumerable<ITaskItem> packages)
    {
        string hash = CalculateHash(packages);
        if (!ShouldRun(project, hash))
        {
            return true;
        }

        if (_fileSystem.Path.GetDirectoryName(project.Path) is string directory
            && !_fileSystem.Directory.Exists(directory))
        {
            _fileSystem.Directory.CreateDirectory(directory);
        }

        _fileSystem.File.Delete(project.Path);
        using Stream stream = _fileSystem.File.OpenWrite(project.Path);
        using XmlWriter writer = XmlWriter.Create(stream, _xmlSettings);
        writer.WriteComment(string.Format(CultureInfo.InvariantCulture, Disclaimer, _time.GetUtcNow(), hash));
        writer.WriteStartElement("Project");

        // Omit version so the outer projects version is implicitly used.
        writer.WriteAttributeString("Sdk", ThisAssembly.Name);

        if (packages.Any())
        {
            writer.WriteStartElement("ItemGroup");

            foreach (ITaskItem package in packages)
            {
                writer.WriteStartElement("PackageReference");
                writer.WriteAttributeString("Include", package.ItemSpec);
                writer.WriteAttributeString("Version", package.Version);
                writer.WriteEndElement();
            }

            writer.WriteEndElement();
        }

        writer.WriteEndElement();
        UpdateHash(project, hash);
        return true;
    }

    private bool ShouldRun(Project project, string currentHash)
    {
        if (string.IsNullOrEmpty(project.HashPath)
            || !_fileSystem.File.Exists(project.HashPath)
            || !_fileSystem.File.Exists(project.Path))
        {
            Log.LogMessage(MessageImportance.Low, Strings.ExtensionProject_DoesNotExist);
            return true;
        }

        string existingHash = _fileSystem.File.ReadAllText(project.HashPath);
        if (existingHash != currentHash)
        {
            Log.LogMessage(MessageImportance.Low, Strings.ExtensionProject_HashOutOfDate, existingHash, currentHash);
            return true;
        }
        else
        {
            Log.LogMessage(MessageImportance.Low, Strings.ExtensionProject_HashUpToDate, existingHash);
            return false;
        }
    }

    private void UpdateHash(Project project, string hash)
    {
        _fileSystem.File.WriteAllText(project.HashPath, hash);
        Log.LogMessage(MessageImportance.Low, Strings.ExtensionProject_FinishedGenerating, hash);
    }

    /// <summary>
    /// Calculates the hash of the current set of extension packages. This is used to determine
    /// if the extension project needs to be regenerated.
    /// </summary>
    /// <returns>The calculated hash.</returns>
    /// <remarks>
    /// The hash calculation uses the following as input:
    /// - The tooling generating the hash itself (so any change to tooling forces a project update).
    /// - The list of extension packages (identity and version).
    /// </remarks>
    private string CalculateHash(IEnumerable<ITaskItem> packages)
    {
        using FnvHash64Function algorithm = new();
        using HashObjectWriter hash = new(algorithm);

        // Verify if the tooling has changed.
        hash.WriteNameValue("version", ThisAssembly.Version.ToString());
        hash.WriteNameValue("moduleId", ThisAssembly.ModuleVersionId);

        hash.WriteArrayStart("packages");
        foreach (ITaskItem item in packages)
        {
            hash.WriteObjectStart();
            hash.WriteNameValue("identity", item.ItemSpec);
            hash.WriteNameValue("version", item.Version);
            hash.WriteNameValue("targetFramework", item.TargetFramework);
            hash.WriteObjectEnd();
        }

        hash.WriteArrayEnd();

        return hash.GetHash();
    }

    private record Project(string Path, string HashPath, NuGetFramework Framework)
    {
        public static Project Create(ITaskItem item)
        {
            string path = item.GetMetadata("ProjectFile");
            string hashPath = $"{path}.hash";
            NuGetFramework framework = NuGetFramework.Parse(item.ItemSpec);
            return new(path, hashPath, framework);
        }
    }
}
